### PR TITLE
Realigning error codes for V2

### PR DESCRIPTION
**Pull request by FinnIckler**
We merged some codes, moved one around and added two new ones

### CODE REVIEW

**Review by dunkOnIT — CHANGES_REQUESTED** [review]
It's missing codes -4003, -4004, -4005, otherwise LGTM

**Comment by FinnIckler** [comment]
it's not, if you look at the full files and not just the diff, they are there

**Review by dunkOnIT — APPROVED** [review]

**Comment by FinnIckler** [comment]
@jonatanklosko Is this the correct way to move a translation from one key to the other, or will this break internationalize?

**Comment by FinnIckler** [comment]
Cool, it wasn't so this should be fine

**Pull request merged**
