### PR TITLE
Add name reason to the competition form

### LINKED ISSUE #3322: Add "reason for name" to competition creation page
From WQAC:

>Problem:
>With the WCA Competition Name Policy in place, we receive requests very frequently of competitions not complying with the name policy. A lot of such requests are very generic names and even the delegates can't explain why they think the name complies with the policy and the only reason we are told is 'the organizer requested for it'. This causes an additional latency loop where we have to communicate with the delegate about this policy and ask them the reason, and eventually change the competition name and ID.

>Request:
>Having the delegates compulsorily fill out this information in the competition request itself can be very helpful for us: reducing our work, having delegates be more conscious of the policy and reduce the competition announcement latency. I have attached a screenshot of how we would like this to look on the website. Just like the reason for competitor limit, this information should also show up in the email we receive when someone confirms a competition.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #3322.

image

### CODE REVIEW

**Comment by jfly** [comment]
Thanks for doing this, @jonatanklosko! However, I am inclined to agree with @pedrosino that this doesn't feel like it will actually solve the problem the WQAC is running into here. Let's wait and see what Akash says on the "Requests from WQAC" email thread.

**Comment by ronaldmansveld** [comment]
Akash' latest reply on this:

> Hi Jeremy,
> 
> I was able to go through the last 100 competition requests in our mailbox - 18 of which needed us to clarify the name from the organizer or had big violations, and there were 7 more cases where the organizer themselves explained the name in remarks section without which we would have to seek a clarification. There are also some other names where an explanation by the delegate would have helped instead of us trying to make sense of it by combining the venue name, season, location. etc. 
> While not everything would be resolved if the delegate was to explain the name, it would surely help and over half of these 25 competitions could be announced faster with the delegate explaining a name (compared to us asking for it). We also believe it can help delegates consciously re-read the name policy before making requests that could be avoided easily by reading it carefully (like submitting a competition with a lowercase initial).
> 
> Regards
> Akash Rupela
> WCA Quality Assurance Committee

I feel we should merge this in, as it does seem it will help them @jfly @jonatanklosko .

**Comment by jonatanklosko** [comment]
I've just rebased the PR, @jfly thoughts?

**Comment by jonatanklosko** [comment]
@DanielEgdal deployed! :ship:

**Comment by DanielEgdal** [comment]
Thanks guys!

**Pull request merged**
