### PR TITLE
Await auxiliary data computation before submitting competition results announcement

### LINKED ISSUE #1902: Disable posting results while compute_aux_data is running
Results team members are not supposed to post results until compute_aux_data is finished running, otherwise competitors will receive results are up notification emails and when they view their profiles, their PBs won't be up to date.

@jonatanklosko, do you think you could look into this? This should hopefully be a simple change.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #1902.

### CODE REVIEW

**Comment by larspetrus** [comment]
To be sure, you need to check on the server side, since an auxiliary computation can have started since the page was generated.

**Comment by jonatanklosko** [comment]
@larspetrus that's right! How would you handle this? I can think of a simple redirection the the edit competition page, people would see the disabled button and the corresponding tooltip then. We could also add a flash message.

**Comment by larspetrus** [comment]
Yeah, a simple "Sorry, wait a few minutes while the auxiliary computation finishes" message should be fine for our purposes.

If this was a professional consumer app there would be a live disabled/enabled button on the page, but I think we have hundreds of bigger priorities.

**Comment by SAuroux** [comment]
In contrast, this concerns an internal admin section and disabling/enabling
buttons on the page would make me feel like a dumb child personally. ;)

This means that a simple message is not only fine, but also to be preferred
in my opinion.

2017-09-04 18:31 GMT+02:00 Lars Petrus <notifications@github.com>:

**Comment by jonatanklosko** [comment]
Changed!

**Comment by jfly** [comment]
@SAuroux, unfortunately, the create results post button is on a big page with a lot of other stuff, and it's a PHP page, so it's not easy for us to change.

@jonatanklosko, this LGTM, but please confirm with @SAuroux that this is acceptable before merging it up.

**Comment by SAuroux** [comment]
@jfly, I don't quite understand your first remark towards me as I said that I prefer no change to the button anyways. 

Just from looking at the code this looks acceptable, but I have to admit that I don't know how this flash warning is displayed in practice. I just tried getting it on staging, but it is not yet merged there currently, right?

**Comment by jonatanklosko** [comment]
@SAuroux it's not on the staging. Here's a screenshot for you =) Let me know if this looks fine, please.

image

**Comment by SAuroux** [comment]
Thanks @jonatanklosko, LGTM! :)

**Comment by jfly** [comment]
@SAuroux, I worry it's not perfectly clear how this works from the screenshot @jonatanklosko included. Just to be clear, here's how you get to that screenshot:

1. Go to https://www.worldcubeassociation.org/results/admin/upload_results.php, and click on "Post the results announcement":

image

2. If compute aux data is being computed, then instead of results being posted, you will see this page:

image

Otherwise, if compute aux is not being computed, then the results post will be created as usual.

**Comment by larspetrus** [comment]
Does the user have an easy way to know when the auxiliary data has finished computing?

I'm mostly wondering if we should say something like "try again in a few minutes" instead.

**Comment by jfly** [comment]
It's not obvious from this flash, but you can check the status of compute aux data by visiting this page: https://staging.worldcubeassociation.org/admin/compute_auxiliary_data. "Try again in a few minutes" or linking to the compute aux data page might help. However, as @SAuroux said, this is an admin page just for the results team. If someone seeing this message doesn't know all about compute_aux_data, then we have bigger problems =)

**Comment by larspetrus** [comment]
OK

**Comment by SAuroux** [comment]
@jfly, it was perfectly clear for me, but thanks for the additional clarification. :)

By the way, I was not able to test this message using the upload script for an already used competition:
1. compute aux data 
2. post announcement (which woudl normally give an error as the post already exists, but I would have expected to see the message now).

Is this desired? In any case, I will test this the next time I post competition results.

**Comment by jonatanklosko** [comment]
Oh wow! I added the guard to the competition announcement link, for some reason I was convinced it was **the** button (no idea why). I'm really sorry about this :disappointed: Now I'm kinda confused as I cannot event find where the results post creation url is called.

**Pull request merged**
