### PR TITLE
Sponsor Acknowledgment

### PR DESCRIPTION
**Pull request by pedrosino**
As per the Board's request

image

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Thanks for taking this on!

For consistency, can you put this policy the first in the list, and with "WCA" at the beginning?

**Comment by pedrosino** [comment]
Hi Alberto

Why would it be the first item in the list? Currently it goes alphabetically (Competition A..., Competition N..., then Dues, Logo).

**Comment by pedrosino** [comment]
As a complement, I'd suggest removing all "WCA " from the list.
For me it's pretty clear that those are WCA Minutes and Policies. What do you think?

**Comment by AlbertoPdRF** [comment]
I think all of them are in chronological order, from newer to older, and they are only ordered alphabetically by pure coincidence.

Also, I prefer to keep the WCA I think.

**Comment by operge** [comment]
I would definitely leave the WCA in front of all of the policies.

As for the order: How about we add the date of release at the end and keep the chronological order? If there is no mention of the release date, I would also go alphabetically.

**Comment by pedrosino** [comment]
I updated as requested.
Out of curiosity, I dug out the old PRs, and turns out we were doing alphabetical, or at least is seems:
https://github.com/thewca/worldcubeassociation.org/pull/2646/files

When Logo was adeed (after Dues was already there), it was placed last on the list, in alphabetical order.

The others were coincidentally in order too. Since I have a little OCD, I'd prefer Sponsor to be last, but that's up to you guys.

**Comment by AlbertoPdRF** [comment]
Oh, if we were doing alphabetically, then we can follow with that. I also like @operge's idea to put the dates and go with chronological order though.

**Comment by AlbertoPdRF** [comment]
LGTM!

**Pull request merged**
