### PR TITLE
Move `/legacy` forum route to `/archive`. Closes #1672.

### LINKED ISSUE #1672: /archive instead of /legacy?
In #1651, we moved the old forum to `/legacy`. My instinct is that this doesn't have the right connotations unless you know English well, or know what it means for software.

I'd like to propose moving it to `/archive` instead.

@jfly, @jonatanklosko , if I want to send a PR without a full checkout, can I just update the single route added in #1651?

### PR DESCRIPTION
**Pull request by lgarron**

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Ahh, sorry but I've just realised that nginx redirects that I set up [in another PR](https://github.com/thewca/worldcubeassociation.org/pull/1663/files) need to be updated as well.

**Comment by jfly** [comment]
I like this change! Let's get the nginx redirects updated and merge this ASAP before people start bookmarking links that have "legacy" in the url.

**Comment by lgarron** [comment]
> Ahh, sorry but I've just realised that nginx redirects that I set up in another PR need to be updated as well.

Added.

**Comment by jfly** [comment]
LGTM!

**Comment by jfly** [comment]
Also, for future PRs, please create a branch on your own fork of the repository. I don't like it when branches litter our top level repo:

image

**Pull request merged**
