### PR TITLE
Changed document request to include option to obfuscate information

### PR DESCRIPTION
**Pull request by Jambrose777**
Simple text change which is more compliant with Data Protection laws.

### CODE REVIEW

**Comment by viroulep** [comment]
I would guess this is a WDPC-requested/approved change, but could you please confirm it?

**Comment by Jambrose777** [comment]
> I would guess this is a WDPC-requested/approved change, but could you please confirm it?

This is what WDPC tells WRT, WDPC, WCT, and Delegates to say whenever they ask for identification via electronic submission, so it should be reflected here too. I can get the approval if needed, just let me know.

**Comment by viroulep** [comment]
Yes please, no need for more people from the WDPC to comment here, I just want to make sure the committee is ok with that changes.

**Comment by Jambrose777** [comment]
2/4 members approve after a week, so I'll say that's an approval :)

**Comment by viroulep** [comment]
Sorry it took so long, I totally forgot about that PR!

**Pull request merged**
