### PR TITLE
Update regs to TNoodle 0.16.3

### PR DESCRIPTION
**Pull request by campos20**

### CODE REVIEW

**Comment by campos20** [comment]
> I'm not too sure why all these commits shows up in the history, but it doesn't look appropriate :s
> Can you please squash/rebase your changes so that there is only one clean commit introducing the new jar?

I thought the other commits were already on "master" of the regs data. I'll squash them.

**Comment by viroulep** [comment]
Thanks!
I think it's just missing the old 0.15.1 (the commit is actually detected as a renaming of 0.15.1 to 0.16.3) to be complete.

**Comment by campos20** [comment]
@viroulep so, do we have an approval now?

**Comment by viroulep** [comment]
No, please see my comment and the actual changes: the jar is detected as *moved* from 0.15.1 to 0.16.3, and although they are indeed different it does mean the 0.15.1 would no longer exist in the source tree after this is merged (whereas we want it to be there for the history page).

**Comment by campos20** [comment]
0.16.3 was aborted due some inconsistencies we found regarding both zip generation and pdf rendering.

**Pull request closed without merging**
