### PR TITLE
Use a more flexible flag library from npm

### PR DESCRIPTION
**Pull request by jonatanklosko**
Switching the flags library to [flag-icon-css](https://github.com/lipis/flag-icon-css)!

There are numerous benefits:
- flags are all SVGs, so we can now set their size freely by manipulating the `font-size` property of an icon
- the repository seems to be active =)
- as you can see in the diff I removed a couple of dirty fixes that are no longer necessary
- I think SVG & CSS is the right way of doing things here
- *in my opinion these new flag images look better and more vivid than the currently used ones*

I've just deployed the change to the staging, there are a couple of places worth looking at:
- [Competitions index](https://staging.worldcubeassociation.org/competitions/)
- Language select in the navbar
- The omni search displaying flags for competitions
- Personal profile page (e.g. [Jeremy](https://staging.worldcubeassociation.org/persons/2005FLEI01), [Philippe](https://staging.worldcubeassociation.org/persons/2008VIRO01), [Lars](https://staging.worldcubeassociation.org/persons/1982PETR01), [me](https://staging.worldcubeassociation.org/persons/2013KOSK01))
- [Translations status](https://staging.worldcubeassociation.org/translations/status)

### CODE REVIEW

**Comment by pedrosino** [comment]
I like it!

**Comment by Laura-O** [comment]
The flags in the profiles look good, the flags in the language selection menu look like they have a white border on the top and left which looks odd to me:
screenshot_2017-11-09_20-36-25

Maybe just remove the box-shadow in the dropdown?

**Comment by jonatanklosko** [comment]
@Laura-O This seems to has to do Chrome actually (I guess that's your browser). It looks fine to me on Firefox. Also when I resize the flag on a person profile page (using Chrome), I get the same weird result as you did, whereas making the flag bigger solves the problem.

Inspecting the issue shown that the `<span>` tags corresponding to the icons has their size computed differently:
- For Chrome I see *17.328 x 13 px*
- For Firefox *17.3333 x 13 px*
As you can see for Firefox is way more precise. The reason behind those numbers is the lib setting `width: 1.33333333em`, that makes the flags respond to font size change nicely.

Any ideas what to do with this?

**Comment by jonatanklosko** [comment]
One, not perfect solution would be making the shadow a bit more subtle, and adding a similar background colour, so instead of seeing these white contrasting borders, one would see borders and shadow almost as if they were one thing. E.g.
```css
flag-icon {
    box-shadow: 0 0 5px rgba(60, 60, 60, 0.3);
    background-color: rgba(60, 60, 60, 0.2);
}
```

Effect:

image

image

@Laura-O Does it look quite fine or is it still noticeable on the screenshots?

**Comment by Laura-O** [comment]
Yep, the screenshot was from Chrome and it looks much better with background color!

**Comment by jonatanklosko** [comment]
I've just updated the code and pushed it to the staging, should be fine now =)

**Comment by jfly** [comment]
Oh this is so awesome, thanks @jonatanklosko!

**Pull request merged**
