### PR TITLE
Use actual class instead of base class name.

### PR DESCRIPTION
**Pull request by viroulep**
Fixes the datetime picker for registrations opening/closing.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
LGTM!

**Comment by jfly** [comment]
Interesting. If this works, then LGTM. But do you have any idea how this used to work? This can't be related to the Ruby 2.4 upgrade, can it?

**Comment by jonatanklosko** [comment]
@jfly check out #software on Slack ^^

**Comment by viroulep** [comment]
Just to make the explanation public:
This is not related to a gem update, Jonatan broke it in af34b3920de6b1e1a677cbb6924053181f7ba5e0, by making some methods class methods instead of instance methods.
It used to work thanks to method overriding: `DatetimePickerInput` inherits from `DatePickerInput`, and the format functions are overriding those of the base class.
This commit restores this behavior by making the methods in the derived class be class methods, and by calling `self.class.method`, which calls the correct method depending on the actual `self` class.

**Comment by larspetrus** [comment]
I'd feel better if there was a test that would go red the next time something like this changes.

**Comment by jfly** [comment]
I added a test for this that fails without @viroulep's change:

```
Failures:

  1) Competition management when signed in as delegate edit can edit registration open datetime
     Failure/Error: expect(page).to have_selector(".bootstrap-datetimepicker-widget .timepicker")
       expected to find css ".bootstrap-datetimepicker-widget .timepicker" but there were no matches
     # ./spec/features/competition_management_spec.rb:171:in `block (4 levels) in <top (required)>'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'

Finished in 15.59 seconds (files took 0.12485 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/features/competition_management_spec.rb:162 # Competition management when signed in as delegate edit can edit registration open datetime
```

It's not the most black box test ever written, but I think it gets the job done.

**Pull request merged**
