### PR TITLE
Update French locale .yml

### PR DESCRIPTION
**Pull request by SK927**
Made by Maxime Lefebvre (2019LEFE02), French Delegate and secretary of the French RO.

### CODE REVIEW

**Comment by gregorbg** [comment]
Thanks for your massive translation work!

Unfortunately, you must've based this off of an outdated version of the YML file, because Git is showing merge conflicts :/

**Comment by SK927** [comment]
Hi Gregor.
Thanks for checking this out. 
Do you mean I used an outdated source file for my translation or that I used an outdated branch to commit my changes?
Everything was marked as synched on Internationalize. 
I have to admit that I suck at using Github and I do not know what I can do to solve this problem.
Let me know :)

**Comment by SK927** [comment]
I think I solved every conflicts, I you want to check.

**Comment by gregorbg** [comment]
Thank you, I checked the file from a technical YML standpoint and it looks good. Note that we cannot change the contents of the translations themselves for obvious reasons :innocent:

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
