### PR TITLE
Add Kazakh translation

### PR DESCRIPTION
**Pull request by jonatanklosko**
Shout-out to Фарид Халитов :tada:  :ship:

### CODE REVIEW

**Review by viroulep — APPROVED** [review]
Looks great thanks!

**Comment by viroulep** [comment]
There is the same issue as with #5717, `kk` is not yet supported by twitter-cldr :(

**Comment by viroulep** [comment]
See twitter/twitter-cldr-rb#239 for the addition of the locale :)

**Comment by jonatanklosko** [comment]
Lovely, thanks!

**Pull request merged**
