### PR TITLE
Allow WRT to choose between replica and main database when generating Tokens

### PR DESCRIPTION
**Pull request by FinnIckler**
I added a select to choose between the DBs and a simple vanilla JS function to update the display. 
React seemed to be a bit overkill for this, but some kind of document onready wrap for `document.getElementById("dbs").addEventListener("change", handleDataBaseOptions)` might be needed. 
I tested this locally on the browser, but it might act differently, so please test on staging first before deploying.

### CODE REVIEW

**Comment by dunkOnIT** [comment]
Just checking in on the status of this PR? Sebastien asked me to keep him updated - let me know if I can help with staging testing or anything!

**Comment by FinnIckler** [comment]
From a code perspective this looks good, if it works on staging I am all for merging it

**Comment by gregorbg** [comment]
This is such a trivial change that I'm almost tempted to ship it as is. Finn, please give a formal code review about the source code changes if you say that they "look good". In the meantime, I will test on staging and report back.

**Comment by gregorbg** [comment]
I've added a small convenience feature that pre-selects the correct database in the PMA dropdown when clicking the "Database" redirect button on the page

**Review by gregorbg — APPROVED** [review]
Finn and I agree that it looks cool. He cannot review because technically it's his PR.

**Comment by dunkOnIT** [comment]
Thoughts on making read-replica the default token generated? I'll make the PR if we agree - my case in favour of it is that read-replica should be the default db accessed, and people should opt-in to the live database only if they need write access

**Pull request merged**
