### PR TITLE
Reuse import logic from v1

### PR DESCRIPTION
**Pull request by FinnIckler**
Not Tested yet, mostly looking for an opinion on if this is good. Will also have to change the export logic to use this format. I don't think it is worth introducing a new format and writing new checks until we allow 3rd parties to just use our API and remove the csv import

### CODE REVIEW

**Comment by FinnIckler** [comment]
https://github.com/thewca/wca-registration/pull/627 for the wca-registration side

**Comment by FinnIckler** [comment]
Also, am I seeing this correctly that the Status field that's in the csv export actually doesn't matter? It looks to me that we just say that if the name is in the csv than it's accepted and if it isn't (but it was before) it's deleted.

**Comment by gregorbg** [comment]
Just curious, I think with V3 this PR is completely redundant?

**Comment by FinnIckler** [comment]
yes

**Pull request closed without merging**
