### PR TITLE
Add registrations from the new Registration Service to the my competitions page

### PR DESCRIPTION
**Pull request by FinnIckler**
This works. The only issue is the tooltip. Which is using `get_registration_status_message_if_registered`. Which for some reason is fetching the registration_status again, even though we already have it here. 

I can rewrite the `competition_message_for_user` to also take the registration to fix this. Thoughts?

### CODE REVIEW

**Comment by gregorbg** [comment]
> I can rewrite the `competition_message_for_user` to also take the registration to fix this. Thoughts?

Yup, but please be as careful as possible about changing the signature. My idea would be something along the lines of:

```ruby
def competition_message_for_user(competition, user, registration = nil)
  messages_to_join << get_registration_status_message_if_registered(competition, user, registration)
end

def get_registration_status_message_if_registered(competition, user, registration = nil)
  registration_status = registration || competition.registrations.find_by_user_id(user.id)
end
```

**Review by gregorbg — APPROVED** [review]
LGTM, just one merge conflict left :smile:

**Comment by FinnIckler** [comment]
RuboCop doesn't like my OpenStruct usage, I thought it was the most elegant solution. I'll just use a struct instead then

**Review by gregorbg — CHANGES_REQUESTED** [review]
You have two choices:
- Tell RuboCop to shut up about the OpenStruct
- Make your struct approach more database-friendly. Right now, you're using the correctly loaded `current_user` variable which contains a `User` model object, read its ID, pass that ID to the new Struct, and read the same User from the DB again using that ID. This is definitely too much. (Same argument applies to `competition_id` parameter)

**Comment by FinnIckler** [comment]
In this case this is true. But if you look at the email PR, I just have the `user_id` and `competition_id` fields. 
I could check if they are already models and then read them if they are?

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
