### PR TITLE
Updating all the places where we tell delegates to contact the Board to instead contact the WCAT.

### PR DESCRIPTION
**Pull request by jfly**

### CODE REVIEW

**Comment by jfly** [comment]
GitHub is still having some issues, so I turned off branch protection to get this merged up.

**Comment by Claster** [comment]
Wouldn't it make sense to also update the following i18n strings?

competitions.update.confirm_success
simple_form.hints.competition.remarks_html
users.mailer.competition_submission_email.confirmed
users.mailer.competition_announcement_email.announced
users.mailer.competition_announcement_email.header

**Comment by viroulep** [comment]
Ah right, I'll do this

**Comment by jfly** [comment]
@pedrosino took care of that email in 69c4d55f736605255e9a9a84abd9f0194ca24a65

**Pull request merged**
