### PR TITLE
Add a missing .erb ending

### LINKED ISSUE #1727: Remaining erb in Regulations
There is some erb rendered here: https://www.worldcubeassociation.org/regulations/history/official/2015-07-01/.
It should actually be interpreted to provide the title for the page.

I'll try to take a look at it in the upcoming week, it should be fairly easy to fix.

### PR DESCRIPTION
**Pull request by jonatanklosko**
This should fix #1727. What would be the best way to test if it works?

### CODE REVIEW

**Comment by larspetrus** [comment]
Obviously the files you changed  will work. What you care about is probably if any new non `.erb` files creep in.

It's easy to write a test asserting that all files in certain directories have names ending in `.erb', or any other pattern.

**Comment by jonatanklosko** [comment]
@larspetrus It's kinda difficult to test this, as it's a completely different (data-only) branch. Also AFAIK it's unlikely to change, thus there isn't a big risk of having more such files.

**Comment by jonatanklosko** [comment]
If it looks good to you, I can just deploy it and see.

**Comment by larspetrus** [comment]
Hey, it was you who asked how to test it :)

If it doesn't need testing, doing nothing is the best solution! But how did these broken files get there?

**Comment by jonatanklosko** [comment]
Ah, I was not clear. I thought about testing it on the staging, but the script goes directly to the worldcubeassociation.org/regulations-data. Actually it seems obvious enough to skip this step.

Philippe plays with this branch time to time, e.g. [here](https://github.com/thewca/worldcubeassociation.org/commit/46163cfc3ecf69ed9cefa2dde7eb672ae556df13).

**Comment by jonatanklosko** [comment]
It did the job!

**Pull request merged**
