### PR TITLE
Allow changing registration fees, even if people have already paid.

### PR DESCRIPTION
**Pull request by jfly**
This is a quick fix for #2123.

@viroulep, will anything break horribly if we merge this up? My thinking is that this will cause people to show up as not fully paid, which will be weird, but workable because their registrations will still be accepted.

### CODE REVIEW

**Comment by viroulep** [comment]
It won't break, but I don't think it's the correct way of handling the use case :p

@pedrosino explained how he handles this [here](https://github.com/thewca/worldcubeassociation.org/pull/1368#issuecomment-285438649).

I think having an "amount owed" would be the correct way of doing this (affected once for all when the registration is created, taken for the current registrations fees).

I understand the fix is urgent, so I'd be fine with merging this now and fixing it "for real" asap later.

**Comment by jfly** [comment]
Got it. Yeah, I agree that having an amount_owed would make sense. Alternatively, if we keep track of changing registration prices over time, we should be able to compute the amount_owed because we know when they registered.

I am going to merge this up right now.

**Comment by pedrosino** [comment]
> Got it. Yeah, I agree that having an amount_owed would make sense. Alternatively, if we keep track of changing registration prices over time, we should be able to compute the amount_owed because we know when they registered.

Usually the amount you pay depends on when you actually pay, not when you first registered.
If you registered at day 1, but prices went up before you paid, you must now pay the update values.

**Comment by jfly** [comment]
Ah yeah, absolutely. Otherwise people would register early and pay later just to get their hands on a cheaper registration fee.

**Pull request merged**
