### PR TITLE
Extract AdvancementConditionsValidator and add tests

### PR DESCRIPTION
**Pull request by tussosedan**

### CODE REVIEW

**Comment by tussosedan** [comment]
Thanks! 😄 
Added a tiny fix to set the comp_start_date local variable only once per outer loop.

A few points I wanted to raise for discussion:
1. The validator_args definition code is repeated in every results validator, would it be a good idea to DRY it up -- perhaps using a shared context? Or it good enough as is?
1. I used one big test example that combines all the advancement errors together (over 2 comps), would it be better to separate it into several examples? Or is it actually better combined?
1. The results creation in the valid and invalid examples is very similar, is it worth being separated into a method with parameters?
1. These tests run locally for 10-20 seconds and even more. As the full tests suite is already taking quite a few minutes, is this acceptable? Tracing the mysql activity shows that creating the factories is generating many separate queries and is taking a long time.

**Comment by viroulep** [comment]
> 1. The validator_args definition code is repeated in every results validator, would it be a good idea to DRY it up -- perhaps using a shared context? Or it good enough as is?

Shared context/examples sound absolutely great to DRY up the results validator tests, but I think we should do that in another PR (where we just do that).

2 and 3 are definitely fine.

4: I didn't have that in mind :s
What's eating up the time? Creating hundreds of results?
If so could we bulk-insert them?

**Comment by tussosedan** [comment]
Yes, aside from the before-suite setup that's taking time, generating hundreds of results would be much faster in bulk than row-by-agonizing-row. How can we do it in bulk with the factories, though?

**Comment by viroulep** [comment]
Hum we can do something a little bit more clever than a simple `create_list`, and unfortunately since `build_list` would also call N `create(:person)` we also need to work around that...
Basically I would do something like that:
```ruby
def build_person(kind, competition)
  if kind == :result
    FactoryBot.build(:person)
  else
    FactoryBot.build(:inbox_person, competitionId: competition.id)
  end
end
def create_results(n, kind, competition)
  persons = []
  results = []
  n.times do
    persons << build_person(kind, competition)
    results << FactoryBot.build(kind, competition: competition, eventId: "333oh", roundTypeId: "1")
  end
  if kind == :result
    Person.import(persons)
    Result.import(results)
  else
    InboxPerson.import(persons)
    InboxResult.import(results)
  end
end
```
It should fire only two sql inserts (one for persons and the other for results).
It's surely possible to do something better since we have access directly to the model and to the model's name as sym, but you get the idea :)

**Comment by tussosedan** [comment]
Oooh interesting, I'll play around with that. And yeah of course we could go straight into the DB, but I think there's value in using the factories as a standard. This idea looks like a great compromise.

**Comment by tussosedan** [comment]
Okay, first of all, the activerecord-import gem we have is awesome :)

To do what you suggested a bit more cleanly, we could add to the results factory something like this (for both person and inbox_person options, with appropriate parameters):

```
    trait :transient_person do
      person { FactoryBot.build(:person) }
    end
```

Then we can use build_list for the results with the persons built and not created. This already cuts the time to a quarter of the time it takes to create_list. However, each build person still fires a SELECT query to verify the ID is unique, which takes the rest of the time.

As this validator doesn't actually use the persons data in the results but rather only counts the entries, I think we can also not actually import the persons into the DB, and even use the same person for all the results without hurting anything?

If we use a single person for all the built results, it's pretty much instant (we can do that by building the person/inbox_person once in the test and passing it as a parameter, or by also adding a trait in the persons factory to override the wca_id uniqueness check and so allow collisions but save time).

What do you think, would this be too ugly?

**Comment by viroulep** [comment]
I'm ok with just using one person, after all we're not looking to test that results make sense, just that they comply with the Regulations :)
Let's go with that ^^

**Comment by tussosedan** [comment]
Okay, done! Changing the draft PR to a normal PR.

**Pull request merged**
