### PR TITLE
Tweaking text on "my competitions" page as per suggestions from Kenneth Lu.

### PR DESCRIPTION
**Pull request by jfly**
## Before:

image

## After:

2017-03-15_13 14 59_1233x169_kaladin

### CODE REVIEW

**Comment by larspetrus** [comment]
Uncontroversial: `will be shown here` -> `are shown`.

Not sure: `which use` -> `that use`? `using`?

Controversial: The added text is too long and will not be read.
Maybe `If you don't see a competition, check its website for what registration system it uses.`

**Comment by ToastyKen** [comment]
[Rule is use "that" if it constrains the subject and "which" if it doesn't, so "that" is appropriate here.]

How's this:
Only competitions that use the WCA registration system are shown here. [br]
If your competition isn't listed here, check the competition website's own competitor list.

**Comment by larspetrus** [comment]
That's even better. Speaks to the user's real need.

**Comment by jfly** [comment]
Updated as per @ToastyKen's latest suggestion, except for the `<br>` tag, which I don't think is worth the effort to implement.

**Comment by larspetrus** [comment]
I assume I don't need to LGTM this explicitly since I already said so in other words.

**Pull request merged**
