### PR TITLE
Move Avatars storage to Amazon S3

### PR DESCRIPTION
**Pull request by gregorbg**
Up until now, user uploaded Avatars were stored in the `secrets` folder on the hard disk of our server. This continues to cause problems because (a) it costs more than S3 storage and (b) it takes ~25 minutes to spin up a new server because we have to sync over several GB worth of picture data.

By storing the Avatars on S3 and caching them via a CloudFront CDN we hope to save costs and we are also a big step closer to enabling multiple server instances with load balancing <3

### CODE REVIEW

**Comment by saranshgrover** [comment]
Woo! So glad to see this being implemented!

**Comment by KerrieJarman** [comment]
Can't comment on the change explicitly but happy to see this move forward

**Review by KerrieJarman — COMMENTED** [review]
To my untrained eye, looks good

**Review by danieljames-dj — COMMENTED** [review]
Thanks for the work @gregorbg. I've gone through the changes, I didn't understand completely as I'm not so fluent in Rails yet. So, I would like to give a neutral thumbs up.

**Comment by gregorbg** [comment]
Having to merge this now due to the urgency of spinning up more servers without distributing 6GB worth of JPEG files among them

**Pull request merged**
