### PR TITLE
Make internal polls visible from Staff panel

### PR DESCRIPTION
**Pull request by Ivan-Brigidano**
I tried and worked fine; was easy to code.

### CODE REVIEW

**Comment by Ivan-Brigidano** [comment]
Thanks @jonatanklosko. It makes sense but still worked locally without it

**Comment by jonatanklosko** [comment]
Yeah, the errors don't show in the dev mode and just display the translation key capitalised, not to bother one to much when. On the other hand tests ensure we don't end up with missing translations.

**Comment by moralsh** [comment]
Not all Staff can view Polls, so either the check should be changed to can_view_poll or the can_view poll should be changed to add all staff. Right now I get a "You are not allowed to view polls" error

**Comment by jonatanklosko** [comment]
Ah wow, that's right! Using `can_view_poll?` sounds good to me! @Ivan-Brigidano could you please create a PR with that change =)?

**Pull request merged**
