### PR TITLE
Always include a contact link for competitions which emails every single organizer and every single delegate.

### LINKED ISSUE #1532: Generate a competition contact link if the user didn't specify one
See #1531. Not all competitions have a contact link (such as https://www.worldcubeassociation.org/competitions/EretumOpen2017):

image

If a contact link is not specificed, we should always generate a contact link that emails all organizer and all delegates.

### PR DESCRIPTION
**Pull request by jfly**
This fixes #1532.

@LinusFresz, could you take a look?

image

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Neat icon, LGTM!

**Comment by pedrosino** [comment]
I'm not that sure the little envelope will be clear to everybody, but I like it. Maybe make it bigger font and red too? :)

**Comment by jfly** [comment]
Bigger looks like this:

image

I'm not up for doing the css work required to vertically center it. @pedrosino, if you want to do some css tweaks after this PR, be my guest =)

(I don't get why we'd change this to red, all our links are orange.)

**Comment by pedrosino** [comment]
Sorry, I meant making "Contact" bigger and red.

I think the small size is fine, though.

On Mon, Apr 17, 2017 at 8:54 PM, Jeremy Fleischman <notifications@github.com

**Comment by pedrosino** [comment]
Or maybe write "Contact the organizers" and the envelope.

On Mon, Apr 17, 2017 at 8:57 PM, Pedro Santos Guimarães <pedrosino@gmail.com
> wrote:

> Sorry, I meant making "Contact" bigger and red.
>
> I think the small size is fine, though.
>
> On Mon, Apr 17, 2017 at 8:54 PM, Jeremy Fleischman <

**Comment by LinusFresz** [comment]
Wow great! Looks awesome Jeremy. :) 
I like the small font, though I am not sure if "contact" or "contact the organizers" is the better option. "contact the organizers" may look a bit too long compared to the other descriptions.

**Comment by jfly** [comment]
It might be worth noting that this is the same "Contact" text that shows up when organizers *do* fill in the contact field. See https://www.worldcubeassociation.org/competitions/RenoSpring2017:

image

**Comment by LinusFresz** [comment]
Yes, I would propose to go with "Contact" to make it consistent. And then we can still see if it changes the amount of people contacting the WCT instead of the organizers.

**Comment by Laura-O** [comment]
> Or maybe write "Contact the organizers" and the envelope.

A bit too late, but I'd recommend to add some text and not only show the icon. On the one hand, for me, it looks like that there is something missing with the envelope icon only. On the other, having some text helps visually impaired visitors.

**Comment by jfly** [comment]
@Laura-O, if you have a better design in mind, feel free to create an issue, or go ahead and send in a PR =)

**Pull request merged**
