### PR TITLE
Schedule editor - Change default to 15 minutes per row

### PR DESCRIPTION
**Pull request by Mollerz**
Fixes first half of #3956

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
This feels very uncontroversial to me, so I'll be merging it up tomorrow unless someone disagrees.

Thanks @Mollerz for submitting the PR!

**Comment by Mollerz** [comment]
> This feels very uncontroversial to me, so I'll be merging it up tomorrow unless someone disagrees.
> 
> Thanks @Mollerz for submitting the PR!

No worries, I have to say it was very difficult to code this one! :P

**Comment by AlbertoPdRF** [comment]
Actually, I tested this locally and wasn't working, as it turns out it's a different file which needs to be edited :stuck_out_tongue: 

Changing [this line on show-schedule/index.js](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/javascript/show-schedule/index.js#L180) does:

image

I'll leave it up to @viroulep to decide if this change (the original one you committed) should be merged as I'm not really sure what it does.

**Comment by viroulep** [comment]
Alberto is right: the line you change is relevant only for the "edit" part of the schedule.
The change is uncontroversial until someone comes and claim 20 minutes per row or 30 minutes per row is a better choice :p

But yeah, 15 minutes is probably a better default choice until we finally bring the parameters editor to the "view schedule" page!

**Comment by viroulep** [comment]
@Mollerz can you update the PR with the change Alberto suggested please?

**Comment by Mollerz** [comment]
> @Mollerz can you update the PR with the change Alberto suggested please?
Done!

**Comment by viroulep** [comment]
Thanks!

**Pull request merged**
