### PR TITLE
Add merch page

### PR DESCRIPTION
**Pull request by dunkOnIT**
Adding a static page for merch, per WMT's request. Still need to confirm where in the menu this will go.

### CODE REVIEW

**Comment by FinnIckler** [comment]
Here is a screenshot, please review any styling/wording choices!

**Comment by FinnIckler** [comment]
Screenshot 2023-07-15 at 10 21 55

**Comment by saranshgrover** [comment]
Thanks @FinnIckler. Here's some small styling requests:



- Can we add this image this image to the top of the page above the WCA Merchandise heading?
- Can we align the "WCA Merchandise" text to the center of the page
- Can we have the two links be buttons instead? Similar styling to the "Learn More" buttons on the WCA homepage

Thats all! Thanks

**Comment by FinnIckler** [comment]
Screenshot 2023-07-17 at 10 55 00

**Comment by FinnIckler** [comment]
Maybe something like this would be better?
Screenshot 2023-07-17 at 11 00 50

**Comment by hariology** [comment]
This looks good :)

**Comment by hariology** [comment]
Flag circular

Maybe we could use this image for Indian flag to make it consistent with the worldwide store image.

**Comment by hariology** [comment]
MerchpageCircular
Like this

**Review by FinnIckler — APPROVED** [review]
LGTM

**Pull request merged**
