### PR TITLE
Increase timeout for CAD

### PR DESCRIPTION
**Pull request by viroulep**
I'll take this to staging, we should be able to see the job end there too, hopefully.

### CODE REVIEW

**Comment by viroulep** [comment]
It worked :)

Merging since it's trivial!

**Comment by viroulep** [comment]
nvm, I really need to go and the tests won't complete in time...
I'll do this later today!

**Comment by jfly** [comment]
Strange... I restarted the build for you and it passed, so I'm going to merge this up.

Thanks!

**Comment by viroulep** [comment]
Thanks Jeremy!

**Pull request merged**
