### PR TITLE
Cutoffs and advancement conditions are actually "better than", not "better than or equal to".

### LINKED ISSUE #2260: Use < or > for cutoffs instead of <= and >= respectively
Regulations state

> 9g2) Whether a competitor proceeds to next phase of a Combined round, must be decided by ranking (best x competitors) or by result (all competitors with a best result **under** x) of the first phase.

And the potential ambiguity has been fixed [here](https://github.com/thewca/wca-regulations/pull/467/files).

The change should apply both to the code and the WCIF document.

### PR DESCRIPTION
**Pull request by jfly**
This fixes #2260.

@viroulep, could you take a look? Thanks!

### CODE REVIEW

**Comment by viroulep** [comment]
so first I can confirm that cutoffs behave as "less than" ("under" in 9g2), and second I feel stupid I did not notice this when reviewing the event page initially and during the translation process...

I'm a bit concerned by the fact that foreign languages will still have the <= sign, and I can see two options here:
 - either update all translations (including updating the hash)
 - or remove any translated string with the "<=" or ">=" sign*

The second option is definitely the easiest I think !

Other than that the changes LGTM.

**Comment by jfly** [comment]
> or remove any translated string with the "<=" or ">=" sign*

I also like this option, but I'm not sure how it will behave with @jonatanklosko's translation app. I know we have talked about this before, but I don't remember what the answer was. @jonatanklosko, could you let us know what would happen if we delete the existing translations?

**Comment by jonatanklosko** [comment]
Removing the keys both in the English version and all the translations (altogether with the corresponding hashes) seems fine to me. I don't expect any issues within the Internationalize app =)

**Comment by jfly** [comment]
Thanks, @jonatanklosko! I've removed the outdated translations.

**Pull request merged**
