### PR TITLE
V2/Edit: Allow Organizers to Edit Registrations after deadline has passed

### PR DESCRIPTION
**Pull request by FinnIckler**
I don't know why I implemented it in that way, because organizers should be able to overwrite it (and it works in the backend).

### CODE REVIEW

**Comment by FinnIckler** [comment]
Should I add a warning to the update prompt?

**Comment by gregorbg** [comment]
> Should I add a warning to the update prompt?

Yes please!

**Comment by FinnIckler** [comment]
I added a message, not 100% sure about the wording, maybe this is something another team should decide?

**Comment by gregorbg** [comment]
Hm, let's not over-bureaucratize things. Launch it with this wording and if anyone has a problem with it, we can still change it in a follow-up PR.

**Review by gregorbg — APPROVED** [review]

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
