### PR TITLE
15(?) years in the making

### PR DESCRIPTION
**Pull request by gregorbg**
Bye-Bye PHP. Oldest commit that I could find dates back to 2008-03-28: https://github.com/thewca/worldcubeassociation.org/commit/0c4e9e7074e9a2b917cddd97415cd38f8fdcdbcb

Note that this PR is removing only the files themselves (and a teensy-tinsy bit of nginx config). The infrastructure is being adjusted in https://github.com/thewca/worldcubeassociation.org/pull/7914 and these two PRs need to be merged in conjunction.

### CODE REVIEW

**Comment by jfly** [comment]
Holy cow!! Amazing

**Comment by coder13** [comment]
I think there's one more line to change :P

./README.md

```
- If you want to run the php part of the website as well, run `docker compose -f docker-compose.yml -f docker-compose.php.yml up`
```

**Comment by gregorbg** [comment]
> I think there's one more line to change :P

_Technically_ there will still be a PHP part even after this PR is merged: PhpMyAdmin per https://github.com/thewca/worldcubeassociation.org/pull/7914

The only notable difference is that we will serve it through its own, well-maintaned Docker image that completely relieves us fro the pain of maintaining PHP configs. But the docker-compose file for php(myadmin) will still exist!

**Review by FinnIckler — APPROVED** [review]
LGTM!

**Pull request merged**
