### PR TITLE
Added eslint for typescript and few import rules

### PR DESCRIPTION
**Pull request by danieljames-dj**
I was working on Delegates Table frontend code in React Typescript, and I was not able to format code with eslint as typescript was not enabled. This PR is mainly to enable typescript in eslint.

This also includes couple of other things like import sorter and unused import remover to make our react code consistent and neat.

### CODE REVIEW

**Comment by gregorbg** [comment]
About adding `yarn install` for GH Actions: That's a general fix over at https://github.com/thewca/worldcubeassociation.org/pull/7975 which should be merged within the next 20 minutes. Please wait and then rebase :)

**Comment by danieljames-dj** [comment]
> About adding `yarn install` for GH Actions: That's a general fix over at #7975 which should be merged within the next 20 minutes. Please wait and then rebase :)

Okay sure, I was just trying out different ways to do it 😅 Thanks for the quick action.

**Comment by gregorbg** [comment]
Done :) rebase and you should be good without any workflow YAML changes

**Comment by danieljames-dj** [comment]
> Done :) rebase and you should be good without any workflow YAML changes

Thanks done. Also, in this PR, I've made few rules 'off' as it was throwing lots of error due to introduction of typescript in eslint. I'll create another PR after merging this which will turn on those rules along with the fixes.

**Comment by gregorbg** [comment]
The Delegates PR is written in vanilla JS, so I'll disregard this PR for now.

**Pull request closed without merging**
