### PR TITLE
Show latest export if the last run failed

### PR DESCRIPTION
**Pull request by FinnIckler**
still needs testing

### CODE REVIEW

**Comment by FinnIckler** [comment]
Tested and moved a bit of logic around

**Comment by FinnIckler** [comment]
Instead: save the timestamp of the last successful run

**Review by FinnIckler — COMMENTED** [review]
I can't approve myself because I opened it, but LGTM

**Review by gregorbg — APPROVED** [review]
Approving on behalf of Finn

**Pull request merged**
