### PR TITLE
Remove subject from email body.

### LINKED ISSUE #997: Subject and title are redundant on Website Comments
See 2nd message:
comments

Maybe not every mail client does this, but it also looks kinda redundant after you open the message:
comm

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #997

### CODE REVIEW

**Comment by viroulep** [comment]
Oh the missing key is `mail_form.request.title`, you want to add `mail_form` to the list of external applications ignored [here](https://github.com/thewca/worldcubeassociation.org/blob/31fbc8bd8ca92053767abc820805a0c73083e26c/WcaOnRails/config/i18n-tasks.yml.erb#L115) to make the i18n test pass :)

**Comment by pedrosino** [comment]
Ah, thanks. I would never know that :)

**Comment by pedrosino** [comment]
I don't know if local servers send emails. And I don't know anything about mailcatcher.
I also think staging does not send emails. Maybe @jfly knows better.

**Comment by viroulep** [comment]
Mailcatcher is designed to catch mail that are not sent because there is no local smtp server working :)

You just run it and visit http://localhost:1080/, whenever a mail is sent from the website in dev it should land here!

However I forgot that this particular form has a captcha check, I just checked it without the captcha and it worked great :)

**Comment by jfly** [comment]
LGTM as well =)

**Pull request merged**
