### PR TITLE
Update zh-CN translation.

### PR DESCRIPTION
**Pull request by 2016WUJI01**

### CODE REVIEW

**Comment by gregorbg** [comment]
Hey there! Thank you very much for your submission.
We usually require that translation updates are submitted by verified translators. In the case of `zh-CN`, the only verified translator is `2008DONG06`. Can you please get a confirmation from him of from your local Delegate that these translations are accurate?

They can confirm by replying directly to this PR, or by sending an email to software@worldcubeassociation.org.
If you would like to contribute more in the future, we can also add you as a verified translator after the confirmation.

**Comment by gregorbg** [comment]
Kindly ping @2016WUJI01

**Comment by 2016WUJI01** [comment]
> Kindly ping @2016WUJI01

I'm alreadly told 2008DONG06, may he have no time to review this pr?
I also see there are other chinese in wst ,Richard Jiankun Peng @notrichardpeng , may he can review this?

**Comment by notrichardpeng** [comment]
I don't have any problems with the translation, Gregor let me know if I can approve this.

**Comment by gregorbg** [comment]
Sure, feel free to approve if you feel that the translations are accurate.

**Pull request merged**
