### PR TITLE
Update to Ruby 2.5.

### PR DESCRIPTION
**Pull request by jfly**
I'm actually running Ruby 2.5 locally and things seem to be working fine. Rspec also passes on [Travis](https://travis-ci.org/thewca/worldcubeassociation.org/builds/328213400#L3688). However, there are a few issues to address before we can switch to 2.5 in production:

## TODO

- [x] Unfortunately, the Brightbox PPA we've been using to install Ruby on our EC2 instances doesn't have Ruby 2.5 yet (see https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng). I've posted a question about Ruby 2.5.0 on https://groups.google.com/forum/#!topic/brightbox-ruby-ubuntu-packaging/NlDfi4gS8C4. If it turns out that the Brightbox PPA has been abandoned, we may have to look into setting up something like `rbenv` in production.
- [x] #2336: Our current version of Rubocop doesn't support Ruby 2.5 (see [this travis failure](https://travis-ci.org/thewca/worldcubeassociation.org/builds/328213400#L1091)). We'll need to get #2336 merged to upgrade to Rubocop 0.52.1 with support for Ruby 2.5.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
@jfly Looks like Brightbox supports for 2.5 now, am I right?

**Comment by jfly** [comment]
Ah, yes it has! See the [blog post](https://www.brightbox.com/blog/2018/02/05/ruby-2-5-ubuntu-packages/) and [mailing list announcement](https://groups.google.com/d/msg/brightbox-ruby-ubuntu-packaging/94tCn97qo_I/U_17UoVNBQAJ).

I'll look into updating this PR accordingly.

**Comment by jfly** [comment]
Our new staging is now live with Ruby 2.5! If nothing comes up over the weekend, I'll deploy this to production on Monday.

**Comment by jfly** [comment]
Merged and spun up a new production server. Everything looks good so far =)

**Pull request merged**
