### PR TITLE
Organizer guidelines fixes

### PR DESCRIPTION
**Pull request by denthebro**
Fixes for the organizer guidelines (all within the en.yml file)

### CODE REVIEW

**Comment by gregorbg** [comment]
Adding Quack to this thread so they can give their consent

**Comment by gregorbg** [comment]
Hm, for some reason GitHub won't let me request a code review from the team so I'll do it the old-fashioned way.

CC @thewca/wqac :partying_face:

**Comment by denthebro** [comment]
> 
> 
> Hm, for some reason GitHub won't let me request a code review from the team so I'll do it the old-fashioned way.
> 
> CC @thewca/wqac 🥳

Oh, I already notified them on slack, don't worry :)

**Comment by DanielEgdal** [comment]
Yep, WQAC has reviewed it now. Ideally this should be merged together with https://github.com/thewca/wca-documents/pull/238 (I believe it has to be the Board who does the merge, and Deni has notified them by mail), but it can be done disjoint.

**Pull request merged**
