### PR TITLE
Adding Swisscubing to the organisations page

### PR DESCRIPTION
**Pull request by gagou9**
:)

### CODE REVIEW

**Comment by viroulep** [comment]
I think you also have to edit the organization static page in order for this to work, you can see how @jfly added Tunisia Cubing in [this](https://github.com/thewca/worldcubeassociation.org/commit/a8b10d4dbda23da6b70dac93a4bd9fa9830089da) commit.

Btw could you squash the 4 commits in 1?

**Comment by gagou9** [comment]
pff I did that locally but didn't git add it. Sorry about that.
Right now I tried the rebase thing and I feel like I broke everything, so will start over from thewca/.

**Comment by gagou9** [comment]
okay, I started all over from a clean fork and a clean clone, and this time submitted all changes.

**Comment by viroulep** [comment]
I did not check the change myself locally , but if the logo and links
appear ok for you on the page,  then the code LGTM!

**Comment by jfly** [comment]
Can you provide a screenshot of this in action? I fear that this won't look so great because the image does not have a transparent background.

Also, this is totally undocumented, but we have a script to automatically size down logos, please run it before committing: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/public/images/organizations/size_down.sh. I don't know where to put this size_down.sh script so that people will know about it. @larspetrus, any ideas? Maybe a test that looks at every image in this directory and asserts that it's a valid size?

**Comment by gagou9** [comment]
Hi!
Many of the images in that folder have no transparent background, so I didn't touch the image yet. I wonder wether that's something we should take care of ?

I had seen that script, but thought (dunno why!) it was automatically run after a push to production.
I just ran it and it said it resized cubingusa.svg and swisscubing.jpg, but cubingusa.svg being svg, of course the content is actually unchanged :)

That's merged, but I have no screenshot to provide, shall I ?

**Comment by gagou9** [comment]
Hm, it seems like this pull request is actually broken. (merging from "unknow repo")

**Comment by jfly** [comment]
> Many of the images in that folder have no transparent background

Oh really? That's surprising to me. Does it look fine because they all have white backgrounds? It would still be nice to get proper transparent images from them.

> I wonder wether that's something we should take care of ?

Nah, that's not our job. I prefer to ask the organization for a transparent image. If they want to show up on the website, I'm sure they're willing to do this small task for us =)

> Hm, it seems like this pull request is actually broken. (merging from "unknow repo")

That's strange, I've never seen that before.

**Comment by gagou9** [comment]
No way to update this pull request because of repo id I guess. Closing. Next one is #1088

**Pull request closed without merging**
