### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by kotarot**
We have finished Japanese translation.
I checked that this translation is up-to-date to the latest English version.
Note that our language code is `ja` but country code is `jp`, so I chose `jp` as `flag_id` in `locales.rb`.
Could you please update this to the staging environment? We'd like to check it before the production is released.

### CODE REVIEW

**Comment by kotarot** [comment]
Test fails 😭

**Comment by jonatanklosko** [comment]
1. At first glance it looks like the test fails due to a key set to `null` (https://github.com/kotarot/worldcubeassociation.org/blob/aae2068f22682f1b41d8a4ff652a54d4e19aeb3c/WcaOnRails/config/locales/ja.yml#L82-L86). This should only happen if you don't have all keys translated in the application, am I right?

2. Could you squash this stuff? Adding a translation is rather simple thing and don't have to involve so many commits =) (e.g. https://github.com/thewca/worldcubeassociation.org/pull/1125/files).

**Comment by kotarot** [comment]
1. Oops, I missed those. I'll fix those. Thanks for the advice!
2. OK. I'll try that.

**Comment by kotarot** [comment]
I fixed `null` terms and rebased all these commits to a single commit.

**Comment by jonatanklosko** [comment]
Awesome! Thanks very much for your work =)

**Comment by jonatanklosko** [comment]
@kotarot I've just deployed stuff and you can see the locale present on [the server status page](https://www.worldcubeassociation.org/server-status).
One thing to note is that two keys are considered *outdated*. I've just realised that you fixed them (the `null` ones) manually and there are not `#originial_hash` comments that my Internationalize app generates. But that will be fixed when you update the translation using the app for the next time =)
+ Tip: as the `ja.yml` file is already here, you can go to your translation edit page (in the Internationalize app) and set *Target URL* to: https://raw.githubusercontent.com/thewca/worldcubeassociation.org/master/WcaOnRails/config/locales/ja.yml

**Comment by kotarot** [comment]
@jonatanklosko OK, Thanks so much! :grinning:

**Comment by kotarot** [comment]
@jonatanklosko  I checked `ja.yml` again, I think the hashes for `null` ones seem to be correct to me. The reason for the two outdated warnings may be caused by keys of `rounds > g` as in https://github.com/thewca/worldcubeassociation.org/blob/7a1045c9931a086fe2a07ec97b697dcbbfd4dbe0/WcaOnRails/config/locales/ja.yml#L117-L123
Even if I use the app, these strange keys are generated.
Dose this phenomenon occur only in my environment?

**Comment by jonatanklosko** [comment]
@kotarot Ah sorry, I didn't pay enough attention probably. You're the first on who actually translated these keys as they were introduced today. I guess there's something wrong with the application, I'll have a look at it, thanks for pointing this out!

**Comment by kotarot** [comment]
@jonatanklosko OK, that's no problem 😄 
I would be glad if you share information when you find out.

**Comment by jonatanklosko** [comment]
Ok, I've found the bug and have just fixed it! Now it works fine, evidence [here](https://github.com/thewca/worldcubeassociation.org/blob/df48beac9e7a33bad9fc36dacb047c25892f1209/WcaOnRails/config/locales/pl.yml#L117-L126).

**Comment by kotarot** [comment]
@jonatanklosko Very cool! It works fine on my environment as well. Thanks a lot!

**Pull request merged**
