### PR TITLE
Timestamps table

### LINKED ISSUE #1576: Discussing a better solution for determining whether linkings computation is needed
(See #1572, where this discussion started.)

The current implementation looks if there are any Results that appeared within the last hour. This implementation has a few quirks to it:

1. This means there's a 1 hour period after results are uploaded where we *always* need to compute linkings, even if the linkings were up to date. For example:
  - Results uploaded at 1am.
  - Generate linkings at 1:10am.
  - At 1:30am, we think we still need to generate linkings, because the most recently modified results is within the last hour (I think this is actually fine because we only schedule work 1 time per hour, but it's still weird)
2. If we miss a cron job, we'll decide never to generate linkings. For example:
  - Results uploaded at 1am.
  - We check at 2:10am if we need to generate linkings, and decide not to. We never end up generating linkings for the results uploaded at 1am.

The weirdness with 1) and 2) above are a result of the fact that we're not taking into account how old the `linkings` table is. I can think of 3 solutions to this (ranked from @jfly's favorite to least favorite):

1. Create a new table to track when jobs were last executed. I could see this being useful for other, future jobs.
2. Use a custom mysql command to figure out when the table was last written to. This was @jonatanklosko's first implementation, but it didn't work because our production version of mysql is out of date. We could look into updating mysql on amazon RDS, though. @larspetrus points out that this would make a future migration to postgresql harder.
3. Add a `updated_at` column to the `linkings` table. This would let us know when the linkings table was last modified, but would also mean storing a whole bunch of extra data we don't need.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #1576.
I'd like to test it on the staging when it's free, so this can wait.

@larspetrus @jfly what do you think?

### CODE REVIEW

**Comment by jfly** [comment]
Beautiful! This is exactly like what I had in mind. LGTM

**Comment by larspetrus** [comment]
I would make it more generic, so it can be used for more purposes. I'd call the table/class maybe `SystemState`, and change `datetime :date` to `string :value`.

You could also claim YAGNI and only generalize the schema when some non date property is needed, and maybe that's fair, but the cost of having it a string is so small I wouldn't bother.

What other system properties are we not recording or keeping in config files or whatnot that would have a good home here? Maybe the last time a backup was made?

**Comment by jfly** [comment]
I am supportive of genericizing this as @larspetrus suggested. I can't think of any additional properties it would make sense to store right now, however.

There are the [page views by locale](https://www.worldcubeassociation.org/server-status) that @larspetrus and I implemented, but I don't know if it's a good idea to add such an expense to every single request that comes into the system.

**Comment by larspetrus** [comment]
Yeah, I don't think the page view count is worth it.

I've used things like this for system settings, but with only one server in the world, it's usually better to hard code those in the code.

I can imagine temporary settings. Like "load=heavy" that would make the app take some shortcuts, or "upload=happening" that could possibly make some operations wait until it's done. This is getting a little far fetched, I know...

Maintenance timestamps like the actual use here is the other obvious category.

I'm perfectly OK with the YAGNI argument winning, BTW.

**Comment by larspetrus** [comment]
Sorry if I delayed this.

One "get things done" technique I like is to flip a coin if a decision is difficult because both options seem equally good. This might be such a time :)

**Comment by jonatanklosko** [comment]
The table is used in this one place, so if we need something more flexible the changes is easy. Tested out on the staging, going to deploy now =)

++ Timestamps seem good for the heavy computation example you've presented.
You create two timestamps `heavy_computation_start` and `heavy_computation_end`. Once you'd like to perform it, then you set *the start marker* to current date and *end marker* to null. Then other code can check if such computation started or not. After the computation is finished you set *the start marker* back to null and *the end marker* to the current date. This way you have an ability wait until it's done as well as have access to the date of last computation (cool for scheduled heavy jobs!).
This is just a first workflow I came up with, might be better =)

**Comment by larspetrus** [comment]
Generic system settings could also go into their own table. None of this will probably ever happen anyway.

**Pull request merged**
