### PR TITLE
Update country band amounts

### PR DESCRIPTION
**Pull request by EdHollingdale**
(don't merge for now, but would appreciate a review to make sure I didn't mess anything up)

Update Dues band base amounts for change to Dues System.

### CODE REVIEW

**Comment by gregorbg** [comment]
If your intention was to change Band 4 Dues to 2.28USD and Band 5 Dues to 3 USD per competitor, then you've done everything correctly :smile: 

Should probably be merged in conjunction with https://github.com/thewca/wca-documents/pull/313, correct?

**Comment by EdHollingdale** [comment]
Hi Gregor, yes that was my intention. I was just wanting someone to make sure I had remembered rebased my fork correctly this time!

Correct, the intention is to merge at the same time as the policy change (and once Board/WFC have reviewed).

**Comment by Jambrose777** [comment]
This percent would also need to be changed from 0.05 to 0.15.

https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_competition_form.html.erb#L328

**Comment by gregorbg** [comment]
> This percent would also need to be changed from 0.05 to 0.15.
> 
> https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_competition_form.html.erb#L328
> 
> Might be good to move this value to be correctly defined somewhere instead of having a random number floating out there :), probably a small clean up issue to create?

Good observation! CC'ing @notrichardpeng as he's currently working on cleaning up the AJAX code for Dues calculation.

**Comment by gregorbg** [comment]
@EdHollingdale Can you confirm that this should be merged now?

**Comment by EdHollingdale** [comment]
> @EdHollingdale Can you confirm that this should be merged now?

Yes, this should be merged now, thanks

**Review by gregorbg — APPROVED** [review]
Approving as per Ed's comment

**Pull request merged**
