### PR TITLE
Add cancelled status to export

### PR DESCRIPTION
**Pull request by oyyq99999**
The field is chosen according to 36dcdf0e

### CODE REVIEW

**Comment by viroulep** [comment]
To be honest I'm not much familiar with the public export, and this part of the website is totally untested...
IIRC @sam596 and @SAuroux have played with the public export: could one of you let us know if adding a field to the exported competitions table would most likely break stuff?

@Baiqiang @oyyq99999 do you know if CubingChina uses the public export to populate its DB? (maybe that's what motivated the change?)

**Comment by oyyq99999** [comment]
I was just curious about whether the new status was exported.
And yes CubingChina is using the export, but that's not the motivation of my PR.

**Comment by sam596** [comment]
@viroulep As far as I can tell, this shouldn't break anything. Just some updated code will be required by people who use it to account for it, otherwise that column will be ignored.

**Comment by viroulep** [comment]
Thanks for the info, merging this!

**Pull request merged**
