### PR TITLE
Capitalize the word "Delegate" consistently through the website (fixes #2934).

### LINKED ISSUE #2934: Capitalization of the word "Delegate" is not consistent across the website
As @jfly pointed out on #2917, the capitalization of the word "Delegate" is not consistent across the website, as for instance can be seen in:

https://github.com/jfly/worldcubeassociation.org/blob/efcd848621418fd54dd6d7c8be42faf2f2dd1511/WcaOnRails/config/locales/en.yml#L380

and:

https://github.com/jfly/worldcubeassociation.org/blob/efcd848621418fd54dd6d7c8be42faf2f2dd1511/WcaOnRails/config/locales/en.yml#L314

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
I hope I caught them all!

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Oops, that's embarrassing :O

**Comment by AlbertoPdRF** [comment]
I can go through the crash course tomorrow. I would prefer not to play with the database though :P Any more places to look at? 

I'll search how to squash the commits tomorrow too!

**Comment by jfly** [comment]
> Any more places to look at?

Besides google docs (which I do not think are worth going through), I think we're good here.

@AlbertoPdRF, @lgarron do you think it could make sense for us to have a WCA style guide? WCA vocabulary such as "WCA" vs "The WCA", "WCA id" vs "WCA ID", "delegate" vs "Delegate", and other pure English stuff such as serial comma and English vs British spelling seem to come up with enough frequency that it would be nice to have a definite set of rules on this stuff.

**Comment by AlbertoPdRF** [comment]
I'm in favor of such a guide.

**Comment by viroulep** [comment]
We use [this](https://github.com/thewca/wca-regulations/blob/draft/style-guide.md) for the WCA Regulations.

**Comment by lgarron** [comment]
I think a style guide sounds good, but only if we make it a part of the process for every document and major wording change to be compared to the style guide.
(I don't want us to maintain rules that we "should" be following, but many forget to look at.)

A pre-submit check for common mistakes would be pretty great for that.

**Pull request merged**
