### PR TITLE
Add Esperanto translation

### PR DESCRIPTION
**Pull request by zeecho**

### CODE REVIEW

**Comment by zeecho** [comment]
I see that the checks are failing because the esperanto translation of fullcalendar has not been merged yet (https://github.com/fullcalendar/fullcalendar/pull/5665). Should I point to the english version for now or should I copy/paste the content of the PR in WcaOnRails/app/assets/javascripts/fullcalendar/locales/eo.js?

**Comment by viroulep** [comment]
Yes please, because even when their PR is merged I doubt they will backport it to fullcalendar 3.9 (and updating our schedule tool to work with 4.x+ would be really a lot of work :s).
If it doesn't work "out of the box", I'd suggest a hacky workaround where you add a eo.js file in [our vendor directory](https://github.com/thewca/worldcubeassociation.org/tree/master/WcaOnRails/vendor/assets/javascripts/fc_locales), based on the already existing files there.

**Comment by zeecho** [comment]
Ok, I'll try that. 

But first, I encounter this error when I try to load any page that needs the list of countries:
2020-09-21-223551_1342x409_scrot

Any idea how to solve it?

**Comment by viroulep** [comment]
Arf it's actually not related to countries, but to sorting data in a specific locale.
We rely on twitter-cldr for that so I've created a PR there.
For the record we ran into something similar for #1321.

**Comment by viroulep** [comment]
Thanks @zeecho for bringing in the 27th locale!

**Pull request merged**
