### PR TITLE
Fix flaky tests with names that require html entity encoding (#2954).

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
I hope this will do it!

### CODE REVIEW

**Comment by jfly** [comment]
Thanks, @AlbertoPdRF! This LGTM. Only comment: If you put "fixes #2954" in your commit message, then it will automatically close the issue once we merge this up.

**Comment by AlbertoPdRF** [comment]
Argh, I thought the issue # was enough.

**Comment by jfly** [comment]
If you put the #, then it will automatically create a comment on the issue, but it won't actually close it. This is useful for workarounds and other things we might do that are related to an issue, but we don't actually want to *close* the issue. See https://help.github.com/articles/closing-issues-using-keywords/ for all the ways of automatically closing an issue =)

**Comment by AlbertoPdRF** [comment]
Got it :)

**Pull request merged**
