### PR TITLE
2018 Regulations history fix

### PR DESCRIPTION
**Pull request by Ivan-Brigidano**
It should work but I'm not very experienced at coding so please revise it!
Solution for Issue #4323

### CODE REVIEW

**Comment by Ivan-Brigidano** [comment]
It doesn't seems to work. Is the 2018 file missing?

**Comment by viroulep** [comment]
The Regulations historically have a separate branch for their data, the history are in there: https://github.com/thewca/worldcubeassociation.org/tree/regulations-data/regulations/build/regulations/history/official

The idea behind that branch is to avoid downloading all tnoodle jars when cloning the website, but it might be worth revisiting that for other files!

So such a change requires two PR: one against `master` to create the link (which you just did), one against `regulations-data` to add the generated htmls/pdf.

Depending on how your comfortable with command line you may want to generate yourself the html/pdf using the [regulations compiler](https://github.com/thewca/wca-regulations-compiler), and create the second PR.
Otherwise we can find someone in the WST to do it for you!

**Comment by viroulep** [comment]
Thanks @Ivan-Brigidano!
I've taken care of the html and pdf files in #4603 so I'll merge this as well.

**Comment by viroulep** [comment]
Looks good to me: https://www.worldcubeassociation.org/regulations/history/official/2018-01-01/
But please let us know if something looks wrong to you.

**Comment by Ivan-Brigidano** [comment]
Everything looks right. Thanks you @viroulep so much for your help!

**Pull request merged**
