### PR TITLE
Add email_to in sanity check category

### PR DESCRIPTION
**Pull request by campos20**
We are going to have a more general sanity check. This should be the first step by letting us to customize the email_to.

### CODE REVIEW

**Comment by gregorbg** [comment]
Strictly speaking, your `structure.sql` changeset is missing `CHARACTER SET utf8mb4`. I recommend that you wait until #8089 is merged before proceeding.

**Comment by gregorbg** [comment]
The "SQL -> Ruby" schema change PR is now merged. You can continue working on this PR now.

**Comment by gregorbg** [comment]
Kindly ping @campos20

**Review by danieljames-dj — APPROVED** [review]
LGTM

**Pull request merged**
