### PR TITLE
Add Visual Guides to Delegate Panel

### PR DESCRIPTION
**Pull request by Nanush7**
Following a suggestion made by Areli Rubí Gordillo Martínez, the WQAC (@thewca/wqac) agreed to add the Visual Guides for Regulations 3j and 5b5f to the Delegate Panel for better visibility and quicker access.

### CODE REVIEW

**Comment by gregorbg** [comment]
Thanks for the submission! Who has the content authority over this PR?
Ie. who can give merge approval, is it WRC or WQAC?

**Comment by Nanush7** [comment]
I'm not sure. In any case, both committees are fine with this.

**Comment by gregorbg** [comment]
In that case I shall take your word for it and just merge this :)

**Review by gregorbg — APPROVED** [review]

**Comment by dmint789** [comment]
NO WAY, YOU CAN'T DO TH... just kidding :)

**Pull request merged**
