### PR TITLE
Registration i18n fixes

### LINKED ISSUE #1153: Model name should be translated
See the following screenshot.
image
image

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #1153.

### CODE REVIEW

**Comment by viroulep** [comment]
`i18n-tasks` and our custom scanner are totally tricked by our way of rendering the event picker...
I would put an `# i18n-tasks-use t('...')` [here](https://github.com/thewca/worldcubeassociation.org/blob/58043a6689896ac03465f03413099f5eb735072f/WcaOnRails/app/views/shared/_associated_events_picker.html.erb#L26).

**Comment by jonatanklosko** [comment]
@viroulep I'd rather avoid putting this comment it with not really related code, as this is a general events picker. Also the key is used just for displaying error messages. What do you think about simply ignoring it and adding some appropriate explanation (as it is currently).

**Comment by jfly** [comment]
I wasn't in love with either solution here, so I decided to look into how to write a custom scanner. Thankfully @viroulep had already written some very useful infrastructure for that, so it was pretty easy to do once I got the hang of it!

See https://hastebin.com/pezelofovo.rb. @jonatanklosko, how do you feel about integrating this? This will teach our i18n scanner to be aware of our crazy custom `associated_events_picker`.

**Comment by jonatanklosko** [comment]
Actually, merged this accidentally instead of another PR, for which I was waiting to pass...

**Comment by viroulep** [comment]
if you didn't deploy, maybe you can just reset the master to what it was and reopen this?

**Comment by jfly** [comment]
> if you didn't deploy, maybe you can just reset the master to what it was and reopen this?

@jonatanklosko, feel free to do that if you want, but you will have to turn off branch protection to be allowed to force push to `master`.

The best solution is probably for @jonatanklosko to send in a followup PR.

**Comment by viroulep** [comment]
oh if we have branch protection on master then don't do what I said!

**Comment by jonatanklosko** [comment]
See #1237.

**Pull request merged**
