### PR TITLE
added setup and teardown options 

### PR DESCRIPTION
**Pull request by darshanvss**
Added Setup and teardown options under custom activities #10419

image

### CODE REVIEW

**Comment by gregorbg** [comment]
I'm not quite sure whether "teardown" is the correct word to use here, as it sounds to me like somebody will move in with sledgehammers and wrecking balls and demolish the whole venue. I am not a native speaker though so happy to defer to other people's expertise.

Also, if we want to go by the book (which I believe we should) a companion PR to https://github.com/thewca/wcif/blob/master/specification.md#other-activities needs to be opened.

**Comment by darshanvss** [comment]
@gregorbg we could maybe change it to 'Take down' or 'Dismantle' ,  or probably 'Pack up' ,'Clear up'.

I'll update the PR once we decide what it should be. I'll raise a companion PR in wcif as well

**Comment by gregorbg** [comment]
Let's just go with teardown. Enough native English speakers convinced me that it's not as daunting as it sounds.

**Review by gregorbg — APPROVED** [review]

**Comment by dunkOnIT** [comment]
Did anyone test this in frontend? There are no translation keys for the new menu options #10539 
image

**Comment by gregorbg** [comment]
Feel free to add some ;)

**Pull request merged**
