### PR TITLE
Improve local date

### LINKED ISSUE #1157: local_time doesn't handle internationalization
From @Baiqiang:

image

local_time is a neat gem we use that allows us to render times in the users timezone. This is hard/impossible for Rails to do, because the server has no idea what timezone its users are in (AFAIK, there's no "this is my timezone" http header). locale_time's clever solution to this problem is to render times in UTC, and then have a little bit of javascript that goes through after the fact and changes the dates to the user's timezone (the client side javascript engine does know what timezone the user is in).

See https://github.com/basecamp/local_time/issues/57 for the local_time issue for internationalization. I see two solutions:

1. Fork local_time and add i18n support to it ourselves, and hope that we can get a PR accepted upstream.
2. Just build our own thing.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #1157.

An example of the formatting:

> Registration closes in about 1 year on *Wednesday, February 7, 2018, 9:17 PM.*

So far is just looks good =)

### CODE REVIEW

**Comment by jfly** [comment]
Hmm... could you include a before and after screenshot, actually? IIRC, we had the user's timezone displayed previously. I think that's very important, so users don't get anxious worrying about what timezone we're telling them this information in.

**Comment by jonatanklosko** [comment]
Before:
screenshot from 2017-01-26 20-48-33
Now:
screenshot from 2017-01-26 20-49-22
Possible way (including time zone name):
screenshot from 2017-01-26 20-50-44

**Comment by jfly** [comment]
I was curious about why Jonatan's example with a timezone shows GMT+1, whereas previously it showed CET. It turns out that the CET comes from parsing `new Date().toString()`, whereas the GMT+1 comes from this `Intl.DateTimeFormat` method (see `new Intl.DateTimeFormat("en", { timeZoneName: "short" }).format(new Date())`). We don't know why these are doing different things on his web browser. Interestingly enough, I see the following on my chrome (running from San Francisco):

```javascript
> new Date().toString()
"Thu Jan 26 2017 15:29:34 GMT-0800 (PST)"
> new Intl.DateTimeFormat("en", { timeZoneName: "short" }).format(new Date())
"1/26/2017, PST"
```

(Note the PST in both places)

I asked @jonatanklosko to dig into this and see what chrome returns for these two methods in various timezones of the world. @jonatanklosko, could you include a copy of your results from your testing here? I think it's very interesting, and would be good to have here for posterity =)

**Comment by jonatanklosko** [comment]
Right, so there are a couple screenshots of the results using Firefox. I've just checked and Chrome seems to behave the same way - on Linux! On Windows however `Date#toString` method includes the long timezone name (both in Chrome and Opera) so it's either platform or version dependent.

screenshot from 2017-01-26 13-53-30
screenshot from 2017-01-26 14-46-09
screenshot from 2017-01-26 15-46-24
screenshot from 2017-01-26 16-47-06
screenshot from 2017-01-26 19-47-41
screenshot from 2017-01-26 21-48-04
screenshot from 2017-01-26 22-48-22
screenshot from 2017-01-26 23-49-08
screenshot from 2017-01-27 00-49-17
screenshot from 2017-01-27 01-19-36
screenshot from 2017-01-27 02-49-56
screenshot from 2017-01-27 03-20-08
screenshot from 2017-01-27 04-50-18
screenshot from 2017-01-27 05-50-49
screenshot from 2017-01-27 07-50-58
screenshot from 2017-01-27 08-51-07
screenshot from 2017-01-27 09-51-35

As you can see `Intl.DateTimeFormat` works great mostly in USA, but other timezone names are not that neat.

**Comment by jfly** [comment]
LGTM!

Thanks for including your results, @jonatanklosko. @lgarron, as our chrome specialist, could you take a quick look and provide your thoughts

**Comment by lgarron** [comment]
[ECMAScript first edition](http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%201st%20edition,%20June%201997.pdf) (linked from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toString)) simply states:

> This function returns a string value. The contents of the string are implementation dependent, but are intended to represent the Date in a convenient, human-readable form in the current time zone.

Based on how these things usually go, I presume the current behaviour of Date.toString() is an accident of history, and possibly preserved because any changes would break compatibility for some sites.

**Comment by jfly** [comment]
Thanks for taking a look, Lucas. It's a shame, because the `toString()` timezone behavior feels more useful / friendly to me. Maybe there's probably some good reason things are the way they are.

**Pull request merged**
