### PR TITLE
Changed edit profile message 

### PR DESCRIPTION
**Pull request by paarthchhabra**
Changed "Contact your delegate" to "Contact the WCA Results Team or your delegate" in accordance with reg 2c2

### CODE REVIEW

**Comment by gregorbg** [comment]
Kindly asking for feedback on the wording @thewca/wrt :smiley_cat:

**Comment by danieljames-dj** [comment]
Sorry for the delayed reply. Regarding the wording, I feel it should be aligned with how 2c2 will be in future. Hence, WRC might be the best people to review this.

@thewca/wrc-team The new text in edit page is as follows:
`You cannot change your name, birthdate, gender, or country. Reason: %{reason}. Contact the WCA Results Team or your Delegate if you need to change any of these.`

Could you please confirm if this wording is fine and will align with 2c2's planned wording for next cycle?

**Review by farhanulju — APPROVED** [review]

**Comment by Nanush7** [comment]
Hi Daniel. Let me check with the Committee :)

**Comment by gregorbg** [comment]
What does "you may expect something like this" mean for the prospect of merging this PR? Is WRC fine with merging the PR as-is?

**Comment by Nanush7** [comment]
Yes, you can merge it.

**Review by gregorbg — APPROVED** [review]
Approved per WRC's comments under this PR

**Pull request merged**
