### PR TITLE
Fix behavior of fixing persons with multiple sub ids.

### LINKED ISSUE #1774: When changing a person's name, fix person updates all past Results with that name, rather than only the ones corresponding to the most recent Person
See https://github.com/jfly/worldcubeassociation.org/blob/35a3c1ba2410f226163f0c244b95264c59e8d460/WcaOnRails/app/models/person.rb#L77-L80.

It's kind of hard to explain this, so I'm just copy pasting @SAuroux's excellent description from the email he sent us:

> This is quite interesting, Apparently fixing competitors is not subId-safe, I did not realize that before. Let me explain what happened there (all about competitor 2015PARK11):
> 
> 1. According to Michael's request, I first updated "Changhee Peter Park"/Korea to "Changhee Peter Park"/United States
> 2. Following Micheal's reply, I then fixed "Changhee Peter Park" to "Peter Changhee Park", expecting this would only concern "Changhee Peter Park"/United States. But apparently this is not the case, it also concerned "Changhee Peter Park"/Korea and therefore the error.
>

### PR DESCRIPTION
**Pull request by jfly**
Fixes #1774.

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Are you guys sure it's a bug? I thought that fixing is a step done for everything in the case of a typo or something like that. In the situation presented by Sebastien I would just either update country&name using sub id at once or in two steps (but still with sub id). If this is not the expected behaviour, then LGTM =)

**Comment by jfly** [comment]
> In the situation presented by Sebastien I would just either update country&name using sub id at once or in two steps (but still with sub id)

Yes, that is what Sebastien should have done, but he made a typo in the name. He created a new sub id with "Changhee Peter Park"/United States, but he really meant to create a new sub id with "Peter Changhee Park"/United States. He tried to remedy this by fixing the newer person's name from "Changhee Peter Park" to "Peter Changhee Park", but that also effected all the results in our database for "Changhee Peter Park"/Korea, which he did not want.

I realize you gave me a LGTM already, but this stuff is subtle, and I'm still concerned I might be understanding it incorrectly, so I'll wait for you to reply again before I merge this up.

**Comment by SAuroux** [comment]
For the record, what you say isn't true. :P

The responsible delegate simply asked for the name to be changed as well
after first only asking to update the country, thus first the update, then
the attempt to fix the name.

2017-07-10 20:15 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
(I may be missing context in the email thread since I was looped in later) If you read the original email closely, you'll see that Michael *did* request both a name *and* country change, not just a country change.

**Comment by SAuroux** [comment]
Dang, you are right! I should probably read mails more carefully. :D

2017-07-10 22:36 GMT+02:00 Jeremy Fleischman <notifications@github.com>:

**Pull request merged**
