### PR TITLE
Replace "FMC".

### PR DESCRIPTION
**Pull request by pedrosino**
Following the discussion between Board, Software and WRC.

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Wouldn't it be better to put again "the 3x3x3 Fewest Moves event" instead of "that event"?

**Comment by pedrosino** [comment]
I don't like repetitions :P 
Maybe "this" instead of "that" is better. Someone with better english knowledge? @jfly @lgarron

**Comment by lgarron** [comment]
I think it would be better to refer to the full event instead of "that", since it doesn't make the text much longer.

**Comment by pedrosino** [comment]
Ok, I changed it to the full name.

**Pull request merged**
