### PR TITLE
Update jquery float thead

### PR DESCRIPTION
**Pull request by jonatanklosko**
Apparently we use a very old version of the plugin, hopefully there are some improvements that make the header less jumpy on scroll.

### CODE REVIEW

**Comment by jfly** [comment]
Thanks! Could we move to using a version from npm instead? https://www.npmjs.com/package/floatthead

When we first added floatthead, we didn't have webpacker, and I guess there was no gem for it...

**Comment by jonatanklosko** [comment]
I'd go for that but still couldn't find any gem for that. We could leverage rails-assets.org to use the NPM version, how does it sound?

**Comment by jfly** [comment]
Oh, I meant: now that we have webpacker, can we instead add this to our package.json? No need to mess around with gems.

**Comment by jonatanklosko** [comment]
Hmm, we use the plugin in [assets/javascript/application.js](https://github.com/thewca/worldcubeassociation.org/blob/953525cfadf5a047940285fa1208ba28a497294e/WcaOnRails/app/assets/javascripts/application.js#L25), and AFAIK we can't just use webpacker package.json dependencies for Rails assets pipeline. I can try initializing the plugin in `javascript/packs/application.js` if that's what you mean?

**Comment by jfly** [comment]
Yep! I think it would work to move it to `javascript/packs/application.js`. It looks like we already moved `autosize`'s initialization over there =)

**Comment by jonatanklosko** [comment]
Assets compilation gives me the following error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'jquery' in '/home/jonatanklosko/projects/worldcubeassociation.org/WcaOnRails/node_modules/floatthead/dist'
```
I'm guessing [that](https://github.com/mkoryak/floatThead/blob/83a95c902e082458f7d12c2c701234410d4d394f/dist/jquery.floatThead.js#L1122)'s why (I removed `require` from the corresponding `.min.js` file locally and compilation succeeded). I guess the problem is that when we `import 'floatthead';` Webpack sees the `require` and looks up `jquery` in `node_modules`, but this fails as our jquery comes from Rails assets.

Cannot think of any reasonable fix without having jquery in `node_modules` (which will happen eventually). Perhaps it's ok to leave that until we port stuff to webpack side of things?

**Comment by jfly** [comment]
Ah, darn. Yeah, I guess we can wait to do this until we've moved jquery into being handled by webpacker.

LGTM!

**Pull request merged**
