### PR TITLE
Change messages at registration page.

### LINKED ISSUE #1095: Editable text section on registration page
It would be really nice to have an area where organizers/delegates could put information regarding registration on the registration form.  Competitors often miss the most important information (how to pay, if we need additional info for lunch/t-shirts, etc.) if it is only left on the website, and may not fill out the form correctly or miss important details.  Here's an example on CUSA:

https://www.cubingusa.com/keepportlandweird2017/register.php

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #1095 

I'm not keen on the text. Feel free to suggest.

Couple screenshots:
check

pending

### CODE REVIEW

**Comment by viroulep** [comment]
Two thoughts:
 - I don't think it totally fixes #1095, I think @KitClement is wishing for an information message editable by the organizers/delegates(?).
 - Regarding the "waiting list" message, I support a clarification (and opened #474 a while back). I guess we need to find a compromise between the fact we don't want to mislead people, and the fact that it is nice to display the registration's position in the waiting list, if there is actually one. Some idea of what the text could include: "Your registration is pending the organizer's approval. If after a few days you haven't been approved, please check the registrations conditions as well as the limit of competitors. There is %{n} people pending approval, you are #%{i} on this list."

**Comment by KitClement** [comment]
Yes, @viroluep interpreted my issue correctly.

**Comment by larspetrus** [comment]
Even reading the new text, I don't fully understand what it tries to communicate.

What does the organizer "approving" the registration mean? Is it only about that competitors also need to pay a registration fee? Can the registration be denied for other reasons? How will I be informed when the organizer approves or rejects me?

**Comment by pedrosino** [comment]
> What does the organizer "approving" the registration mean? Is it only about that competitors also need to pay a registration fee? Can the registration be denied for other reasons? How will I be informed when the organizer approves or rejects me?

All registrations are initially put on the "waiting list", which means "pending approval". Organizer has to approve each one before they appear publicly. That may include payment of a fee. Competitors receive an email once their registration is approved (or deleted or something else).

**Comment by larspetrus** [comment]
I see. Is there a way for the organizer to communicate with the applicants other than approving or denying?

A piece of competition specific text to include in this response would be better than asking them to check the web site.

Anyway, my attempt at new text in the current real world:

_Your registration is pending. For approval, you probably need to pay a registration fee. Check the competition site for details._

**Comment by pedrosino** [comment]
Organizer has access to all registered competitors' emails.

We could have what Kit asked, a customisable message that would appear at registration page and on the notification email just after someone registers.

I would suggest changing the "...you probably need..." to "...you may need..."

**Comment by larspetrus** [comment]
Yeah, Kit's idea is the same as mine.

I don't think the exact phrasing is important enough to delay this any further. Can you just decide on one and push it out?

In other words: **LGTM**

**Comment by jfly** [comment]
This also LGTM. @pedrosino, is there a reason you haven't merged this up yet? It feels like an improvement upon what we currently have.

**Comment by pedrosino** [comment]
I was going to do it the other day, but forgot.
I just pushed a new message and will merge.

**Comment by Jambrose777** [comment]
I still think a plain editable text box for organizers to edit would be the ideal solution to this. (Unless I'm missing a big issue with doing this).

With The way it is set up after the commit, there is still some confusion from users, especially with competitions that are full and using registerstion as a waiting list.

The benefits with an editable text box that I can think of are:
1) this provides a payment link exclusively to people that register, so we no longer have to deal with people who pay but do not register.
2) makes a clear place for competitors to go to know that they need to pay (opposed to just referencing some other webpage), and they are immediately presented this option after registering.
3) the organizer can make it clear whether the comeptition is full or not to notify the comeptitor if there is a waiting list or not.

Albeit confusing, I liked how before the commit it showed your placement on the waiting list (however if there would be a way to toggle this to turn on when the competition is full, it would be less confusing).

**Comment by jfly** [comment]
@Jambrose777, can we wait and revisit this sometime next month after payments have gone live on the WCA website?

**Comment by Jambrose777** [comment]
@jfly Yes! Especially if that will be changing the registration procedure entierly.

**Pull request merged**
