### PR TITLE
Change `disabled` to `readonly` in Delegate Reports' schedule field.

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
Thanks to @Epride for the catching the issue! A few Delegate Reports have already gone through without their schedule links because of this, so I will merge it up as soon as tests pass!

### CODE REVIEW

**Comment by jfly** [comment]
What happened here? Was the use of `disabled` causing the schedule links to get cleared in the backend? If so, does that mean we're missing some sort of validation on the backend to prevent this sort of thing?

**Comment by AlbertoPdRF** [comment]
I'm not exactly sure of what happened here -- I just rushed finding a solution to the bug, as some reports had already been submitted without a link to the schedule. Should I dig deeper into this?

**Comment by jfly** [comment]
It's usually great to fix things quickly, but I think it's also nice to take the time to fully understand what went wrong, if only so we learn a bit more for next time. In this particular case I have a few questions:

1. I don't understand why changing this from `disabled` to `readonly` changed anything.
2. Why wasn't this always a problem? Did something change recently that broke this?
3. Should we add a presence validator to `schedule_url` and `discussion_url`? Right now we just validate that they're empty, or a valid url: https://github.com/jfly/worldcubeassociation.org/blob/fd5a534f7b118cb192225d911aae4fcd98122969/WcaOnRails/app/models/delegate_report.rb#L26-L27

**Comment by AlbertoPdRF** [comment]
Keeping your numbering:

1. While trying to understand what was going on I found [this question](https://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht) on stackoverflow, the replies to which made me try the `readonly` attribute instead of the `disabled` one
2. This was always a problem since #4279 was merged (almost one day before this one)
3. Sure! Adding a `presence: true` sounds good to me. I can proceed with that

**Pull request merged**
