### PR TITLE
Give @tussosedan access to our staging server so he can investigate MySQL 8.0.

### PR DESCRIPTION
**Pull request by jfly**

### CODE REVIEW

**Comment by jfly** [comment]
I'm testing this out on staging now.

**Comment by viroulep** [comment]
tbh I'd just manually cat his keys manually to staging

**Comment by jfly** [comment]
Ah, my thinking was if someone else ran chef, or if Alex himself ran chef on the staging server, he'd lose access.

**Comment by viroulep** [comment]
I'll close this as it's not relevant anymore (@tussosedan is a WST member now :)), but it's nice to have the diff at hand in case something similar shows up :)

**Pull request closed without merging**
