### PR TITLE
Add trophy icon to championships in the my_competitions tables

### PR DESCRIPTION
**Pull request by AxelFl**
Issue #4508 
Places the trophy icon to the right of the names of championships in the my competitions view
Also has the tooltip indicating the type of championship

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Also note that some tests are failing, specifically [this](https://github.com/thewca/worldcubeassociation.org/blob/9a6bfcef55d8c38dfdd6488b30df993b525ac81d/WcaOnRails/spec/views/competitions/my_competitions.html.erb_spec.rb#L20) and [this](https://github.com/thewca/worldcubeassociation.org/blob/9a6bfcef55d8c38dfdd6488b30df993b525ac81d/WcaOnRails/spec/views/competitions/my_competitions.html.erb_spec.rb#L31).
My guess would be that whitespaces cause the problem, I think it's fine to not assert the whole html tags, but just competition names. Let me know if you have any troubles with that!

**Comment by AxelFl** [comment]
Screenshot from 2020-01-11 14-59-56
Screenshot from 2020-01-11 15-02-39
Screenshot from 2020-01-11 15-03-11

How it looks in the menu.

I removed the <tb> tags around the tests since they are on new lines after the change. But it still checks the name and working link.
Maybe there should be a test for championships now as well?

**Comment by jonatanklosko** [comment]
Perfect, thanks!

> Maybe there should be a test for championships now as well?

If you feel like adding one, I'm all for it =)

**Comment by jonatanklosko** [comment]
Thanks a lot!

**Pull request merged**
