### PR TITLE
Make events buttons look better.

### LINKED ISSUE #1555: Event counter on registration breaks up the design
I don't know if this was intentional, but the All | Clear buttons look off:

Admin view
events

Normal registration
events reg

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #1555 

After:
ev

ev2

### CODE REVIEW

**Comment by pedrosino** [comment]
Seems too easy to be true...

**Comment by jfly** [comment]
Nice, simple change! I'm no designer, but I'm not sure it's actually more pleasing to my eye, since it breaks up the nicely aligned labels and forms.

Did you look into moving the "all" and "clear" buttons onto a new line?

If you're pleased with this change, then I am not opposed to you merging this up, so LGTM.

**Comment by pedrosino** [comment]
Ah, I see what you mean. I'll try with the buttons on a new line, maybe it is better indeed.

**Comment by pedrosino** [comment]
It looks good as well to me:
button events

**Comment by jfly** [comment]
Love it! Please sanity check that it looks good on mobile, and then LGTM =)

**Comment by pedrosino** [comment]
mobile
I like it.

**Comment by jfly** [comment]
:shipit: :ship:

**Pull request merged**
