### PR TITLE
Removing (Hiding) WDPC

### PR DESCRIPTION
**Pull request by Jambrose777**
With the new Motions just approved. The WDPC will be removed. 

- I've removed the email syncs (I'm not sure if there is something needed to happen outside the scope of this PR for that).
- One option we might want to explore instead would be if we want WDPC addresses to forward to the results team's email? cc: @thewca/board for thoughts
- I've updated the team to be hidden so we preserve the history.
- ~~Need to Add the @thewca/board as an approver for once the motions are updated.~~ (Motions are updated)
- The end dates of the team members will need to be updated on the website after this is merged.

### CODE REVIEW

**Comment by cubewhiz** [comment]
The Board discussed in our meeting earlier today that we will create a forward for the WDPC addresses to WRT.

**Comment by Jambrose777** [comment]
> The Board discussed in our meeting earlier today that we will create a forward for the WDPC addresses to WRT.

Awesome, @Whoever reviews this, I'm not sure how to set up such from the software perspective.

**Comment by cubewhiz** [comment]
> > The Board discussed in our meeting earlier today that we will create a forward for the WDPC addresses to WRT.
> 
> Awesome, @whoever reviews this, I'm not sure how to set up such from the software perspective.

I think the change is only necessary in the G Suite Admin. The Board (or any WST member with SuperAdmin access on GSuite) can make this change.

**Review by jonatanklosko — APPROVED** [review]
LGTM, let me know if it's ok to proceed with the migration!

**Pull request merged**
