### PR TITLE
Update Bylaws and add minute

### PR DESCRIPTION
**Pull request by pedrosino**

### CODE REVIEW

**Comment by pedrosino** [comment]
The Bylaws file was meant to be a replacement. I think I forgot to "add" the deleted file.

**Comment by pedrosino** [comment]
I talked to @jonatanklosko and this is correct. I'll merge now.

**Comment by jfly** [comment]
Gotcha! I guess github doesn't do a good job of showing that a binary file changed, rather than that it's brand new?

image

**Comment by pedrosino** [comment]
I think if you "add" the deleted file it will appear like at https://github.com/thewca/worldcubeassociation.org/pull/2459/files

But everything looks fine on the page now.

**Comment by jfly** [comment]
Ohh, so you edited 2 files here? From the PR title, it sounded like you added a new one.

**Comment by pedrosino** [comment]
I edited one and added a new one.

**Pull request merged**
