### PR TITLE
Add permanent link for database export by simply setting up a symlink for each of the zip files.

### LINKED ISSUE #60: Permalink for db export
The zip should contain the version number and date, but the URL should stay constant.

### PR DESCRIPTION
**Pull request by jfly**
(Pair programmed with @coder13)

Dead simple, but it works. This fixes #60.

You can see it live on https://staging.worldcubeassociation.org/results/misc/export.html.

image

### CODE REVIEW

**Comment by jfly** [comment]
We need to verify that this does not break the [wca-workbook-assistant](https://github.com/thewca/wca-workbook-assistant).

CC-ing some other people who I know do use the database export: @Luis-J-Ianez @roudai @speedsolve @timreyn.

**Comment by timreyn** [comment]
Awesome!  This shouldn't break cubingusa, which looks for the old-style URL in a way that won't break.

**Comment by coder13** [comment]
LGTM

**Comment by Luis-J-Ianez** [comment]
Roger!

**Comment by viroulep** [comment]
Cool, I use it too and I remember wishing we had a permalink :)

**Comment by jfly** [comment]
Merged and reran the public export. Check it out: https://www.worldcubeassociation.org/results/misc/export.html

**Pull request merged**
