### PR TITLE
Markdown editor improvements

### PR DESCRIPTION
**Pull request by jfly**
Move from the abandoned SimpleMDE to EasyMDE.

Experiment with uploading images directly to the WCA website for use in markdown posts + delegate reports (this should help out with #4309).

NOTE: We should not merge this up until
Ionaru/easy-markdown-editor#109 is merged and
released. Then we should update this diff to pull in latest version of
EasyMDE with these fixes.

### CODE REVIEW

**Comment by jfly** [comment]
> One concern I have is that we use markdown editors in places where uploading is not desirable (e.g. competition form).

Oh, good call! I totally forgot that we use them there. I'll go through all our markdown editors and update them to explicitly support image uploads or not.

**Comment by jfly** [comment]
I went through our list of markdown-editor's on the website, and ran into  our competition tabs code https://github.com/thewca/worldcubeassociation.org/blob/a7c6eb3413c2525296c5a94049256049a3dd276f/WcaOnRails/app/views/competition_tabs/_competition_tab_form.html.erb#L4. I'm not sure what to do here, as most anyone could be a competition manager, but it also seems quite useful to allow uploading pictures here. Maybe we should just allow uploading pictures if you are logged in?

**Comment by jonatanklosko** [comment]
We could allow competition managers to upload as well. As far as I can tell normal users have no markdown editors, so it doesn't make sense to grant them the permission (while an attacker could send upload requests directly).

**Comment by jfly** [comment]
Interestingly enough, while poking around, I discovered the following routes:

```
                               rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
                        rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
                               rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
                        update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
                             rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
```

In particular, the `rails_direct_uploads` one looks interesting. It looks like anyone can use that endpoint to upload... anything? to our S3 bucket. Docs here: https://guides.rubyonrails.org/active_storage_overview.html#direct-uploads. There's a SO thread about this here: https://stackoverflow.com/questions/52497044/how-to-disable-auto-generated-routes-by-active-storage, too. Pretty strange.

> We could allow competition managers to upload as well

Unfortunately, we don't actually have a "is this person managing any (upcoming?) competitions" helper, we only have a `can_manage_competition?(competition)` helper. I've gone ahead and added a `can_manage_any_not_over_competitions?` method and updated `can_upload_images?` to look at this.

**Comment by jfly** [comment]
I did some research, and unfortunately, I don't see a good way to add validations to this new endpoint. I've filed https://github.com/thewca/worldcubeassociation.org/issues/4380 to track improving this.

**Comment by jfly** [comment]
The build is failing with some JsHint related issues. I've fixed that over in https://github.com/thewca/worldcubeassociation.org/pull/4381.

**Comment by AlbertoPdRF** [comment]
We should probably let people know of this cool new feature! Can you send in a quick announcement? :slightly_smiling_face:

**Pull request merged**
