### PR TITLE
Update WQAC Competitor Tutorial to version 2019-10-21

### PR DESCRIPTION
**Pull request by suushiemaniac**
Changelog:
- Include a header that makes the reader aware of translations
- Add a bottom section that lists all available translations including a disclaimer
- Add Russian translation by 2019VIKH01 (proofread by Vasily Stasyev, Ilya Tsiareshka, Nikolay Masson)

### CODE REVIEW

**Comment by suushiemaniac** [comment]
Open for (possibly public) feedback right now, will be merged in T-48 hours.

**Comment by suushiemaniac** [comment]
[WCA_Competition_Tutorial.pdf](https://github.com/thewca/worldcubeassociation.org/files/3749950/WCA_Competition_Tutorial.pdf)

**Comment by Ivan-Brigidano** [comment]
@suushiemaniac do you plan to add the scramblers signature on the tutorial?

**Comment by suushiemaniac** [comment]
No. The rationale behind this decision is that the target audience of the Competitor Tutorial are absolute beginners. They are usually not suitable for scrambling anyways, and we recommend Delegates to only assign scrambling duties to experienced people who know what they're doing.

As a perspective, we may include a section with more "advanced" tips in the future.

**Comment by TimWCA** [comment]
There is Russian Translation?

**Comment by TimWCA** [comment]
@suushiemaniac There is Russian Translation?

**Comment by suushiemaniac** [comment]
The Russian translation can be found at the bottom of the document. Future translations will be linked there as well.

**Pull request merged**
