### PR TITLE
Rename Rounds table to RoundTypes. I hope this works, our PHP is untestable

### PR DESCRIPTION
**Pull request by jfly**
Paired with @FatBoyXPC. After this gets merged up, I plan to add a proper `rounds` table that will store information about all the rounds of competitions.

@larspetrus, just FYI, since we were talking about this earlier today.

### CODE REVIEW

**Comment by larspetrus** [comment]
I liked `RoundFormat` better. Why the change? I see there are some `roundFormatId`s still in the code.

I would have thought it's really hard to change the PHP code to work with the new table structure?

**Comment by jfly** [comment]
> I liked RoundFormat better. Why the change? I see there are some roundFormatIds still in the code.

Whoops! I changed my mind halfway through when I realized that we already have a thing called a "round format": a round format tells you how many solves you'll do in the round, and how to compute the average. This is stored in our [`Formats` table](https://github.com/thewca/worldcubeassociation.org/blob/745e6307e34716909b2ac80038437e851ff4c82d/WcaOnRails/db/seeds/formats.seeds.rb).

This PR is not related to round format, it's [something else](https://github.com/thewca/worldcubeassociation.org/blob/745e6307e34716909b2ac80038437e851ff4c82d/WcaOnRails/db/seeds/rounds.seeds.rb). A first round is different than a second round which is different from a combined first round which is different from a final round. I don't know of a good word for this concept, which is why I went with the half hearted "type". I'm totally open to changing it if you have a better name, but in the fullness of time, I'd like to get rid of this concept entirely in favor of a "nth_round" concept instead.

> I would have thought it's really hard to change the PHP code to work with the new table structure?

Yes, well look at the diff! And I have very little confidence that anything works because the PHP code is totally untested.

**Comment by jfly** [comment]
Updated to use `roundTypeId` everywhere, instead of the poorly named `roundFormatId`.

**Comment by larspetrus** [comment]
Aha. That just looks like some stray properties/ functions of a proper Round class. Hard to see why it would even be in the DB.

Clarification: By "hard to change" I meant the new Rounds table, not the rename.

**Comment by jfly** [comment]
> Clarification: By "hard to change" I meant the new Rounds table, not the rename.

Let's talk about the new Rounds table in my next PR that introduces that table =)

**Pull request merged**
