### PR TITLE
1liner

### PR DESCRIPTION
**Pull request by dunkOnIT**
Tried redeploying main as (I think) Finn suggested but staging is still on an old commit which 404's the competition pages (??)

> 
> message:F, [2024-06-10T07:03:04.192830 #534] FATAL -- : [5a8809e4-34b8-4ed7-9207-1abeb725e191]   
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] ActionView::Template::Error (the server responded with status 404):
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     288:         <% end %>
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     289:       <% end %>
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     290: 
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     291:       <% @competition.warnings_for(current_user).each do |field, message| %>
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     292:         <%= alert :warning, message, note: true %>
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     293:       <% end %>
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]     294: 
> [5a8809e4-34b8-4ed7-9207-1abeb725e191]   
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] lib/microservices/registrations.rb:71:in `competitor_count_by_competition'
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] app/models/competition.rb:420:in `registration_full?'
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] app/models/competition.rb:474:in `warnings_for'
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] app/views/competitions/_nav.html.erb:291
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] app/views/competitions/show.html.erb:3
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] lib/middlewares/warden_user_logger.rb:13:in `call'
> [5a8809e4-34b8-4ed7-9207-1abeb725e191] lib/middlewares/fix_accept_header.rb:14:in `call'

### CODE REVIEW

**Comment by dunkOnIT** [comment]
@thewca-bot deploy staging

**Comment by FinnIckler** [comment]
this is not how to redploy main on staging

**Comment by FinnIckler** [comment]
you can just use the action

**Comment by dunkOnIT** [comment]
I did try use the Deploy action you showed me before I went on leave, but it didn't result in a redeploy to staging (at least, as far as I could tell)

**Comment by FinnIckler** [comment]
It certainly does. You can always check the current git commit at https://staging.worldcubeassociation.org/server-status

**Comment by dunkOnIT** [comment]
That's what I was referencing - but just realising I should have checked AWS for the deployment. My bad!

**Pull request closed without merging**
