### PR TITLE
Add schedule to WCA competitions API

### PR DESCRIPTION
**Pull request by UnsolvedCypher**
Allow accessing the schedule via the WCA API

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
Could you also throw in a quick test for this?

**Comment by UnsolvedCypher** [comment]
@FatBoyXPC How would you suggest testing this? Comparing the entire JSON to the expected response JSON? Or comparing the fields one-by-one? Or perhaps just comparing a few fields?

**Comment by viroulep** [comment]
FYI you can already get it through the WCIF!
I guess it's simple to implement and may be nicer for those willing to only get the schedule though.

**Comment by UnsolvedCypher** [comment]
@viroulep The benefit here is that WCIF requires authentication but the schedule is public information so authentication shouldn't be necessary. You can get information like who is registered without having to authenticate already, so I think it would be nice to do the same for the schedule :)

**Comment by viroulep** [comment]
Oh definitely!
I thought anyone could get public parts of the WCIF through the WCIF endpoint ^^

**Comment by jfly** [comment]
I think my preference would be to do one of these:

1. Add support for a "public wcif" endpoint, or
2. Update the existing /wcif endpoint to automatically return only the public information if they aren't authenticated.

2) might be confusing if they are meant to be authenticated, but have some bugs in whatever software they're using.

**Comment by UnsolvedCypher** [comment]
@jfly So would both of these options deprecate the /results, /competitors, and /registrations endpoints? Or would they exist alongside the WCIF?

**Comment by jfly** [comment]
Deprecating those endpoints feels right to me. If we want "more efficient" apis like those, we could provide a `/wcif/results` that would only return the results subtree of the wcif.

**Comment by UnsolvedCypher** [comment]
@jfly Wouldn't that be the same thing as we have right now, other than changing the paths? Or would the implementation details be different?

**Comment by jfly** [comment]
I think it would be pretty similar, except we'd also make it possible to query `/wcif` even if you're not logged in (or something similar, as I mentioned on https://github.com/thewca/worldcubeassociation.org/pull/4436#issuecomment-520489138)

**Comment by FatBoyXPC** [comment]
I'm not sure I'm a fan of removing the other endpoints in favor of making `wcif` "queryable". I consider these to be different things (the wcif being a single competition worth of data). What if I don't want all of the competition data? The downside to what I'm saying is having multiple sources of truth :thinking: 

@UnsolvedCypher for future reference:

> Comparing the entire JSON to the expected response JSON?

Yes, but maybe my testing standards are a bit more strict than others and possibly than this project. My opinion, though, is we know exactly what our inputs are so we should assert against exact output, too.

**Comment by UnsolvedCypher** [comment]
@jfly Would you like me to add tests here and add the schedule endpoint then move it (and other endpoints) to /wcif under a separate PR? Or do you want to close this PR and handle this separately?

**Comment by jfly** [comment]
Go ahead and add a test, and I think we can merge this up.

We can rejigger the API another day.

**Comment by UnsolvedCypher** [comment]
Does the following look like a reasonable test? The JSON is really long, so it takes up quite a bit of space here but I'm not sure of a better way to do this.

```
    it 'displays schedule' do
      get :schedule, params: { competition_id: competition.id }
      expect(response.status).to eq 200
      parsed_body = JSON.parse(response.body)
      print(response.body)
      expect(response.body).to eq '{"startDate":"2014-02-03","numberOfDays":3,"venues":[{"id":1,"name":"Venue 1","latitudeMicrodegrees":123456,"longitudeMicrodegrees":123456,"timezone":"Europe/Paris","rooms":[{"id":1,"name":"Room 1 for venue 1","color":"#304a96","activities":[{"id":1,"name":"Some name","activityCode":"other-lunch","startTime":"2014-02-03T12:00:00Z","endTime":"2014-02-03T13:00:00Z","childActivities":[],"extensions":[]},{"id":2,"name":"another activity","activityCode":"333fm-r1","startTime":"2014-02-05T10:00:00Z","endTime":"2014-02-05T11:00:00Z","childActivities":[{"id":3,"name":"first group","activityCode":"333fm-r1-g1","startTime":"2014-02-05T10:00:00Z","endTime":"2014-02-05T10:30:00Z","childActivities":[],"extensions":[]},{"id":4,"name":"second group","activityCode":"333fm-r1-g2","startTime":"2014-02-05T10:30:00Z","endTime":"2014-02-05T11:00:00Z","childActivities":[{"id":5,"name":"some nested thing","activityCode":"333fm-r1-g2-a1","startTime":"2014-02-05T10:30:00Z","endTime":"2014-02-05T11:00:00Z","childActivities":[],"extensions":[]}],"extensions":[]}],"extensions":[]}],"extensions":[]}],"extensions":[]},{"id":2,"name":"Venue 2","latitudeMicrodegrees":123456,"longitudeMicrodegrees":123456,"timezone":"Europe/Paris","rooms":[{"id":2,"name":"Room 1 for venue 2","color":"#304a96","activities":[{"id":1,"name":"Great round","activityCode":"333-r1","startTime":"2014-02-03T10:30:00Z","endTime":"2014-02-03T11:00:00Z","childActivities":[],"extensions":[]},{"id":2,"name":"Great round","activityCode":"333oh-r1","startTime":"2014-02-03T10:30:00Z","endTime":"2014-02-03T11:00:00Z","childActivities":[],"extensions":[]}],"extensions":[]},{"id":3,"name":"Room 2 for venue 2","color":"#304a96","activities":[],"extensions":[]}],"extensions":[]}]}'
    end
```

**Comment by jfly** [comment]
We already have confidence that that `schedule_wcif` method does the right thing. I think it's fine to just assert on one piece of the response, like this:

```ruby
    it 'displays schedule' do
      get :schedule, params: { competition_id: competition.id }
      expect(response.status).to eq 200
      parsed_body = JSON.parse(response.body)
      expect(parsed_body['startDate']).to eq ...
    end
```

**Pull request merged**
