### PR TITLE
Reduce the number of unicorn workers in light of our recent OOM situations.

### PR DESCRIPTION
**Pull request by jfly**
This is meant as an alternative to #1323. I don't want to merge both that PR and this one up, because I want to reduce the number of variables when trying to track this down.

### CODE REVIEW

**Comment by jfly** [comment]
Actually, I'm just going to merge this up immediately because our server has been hurting for the last few days. Afterwards, we can discuss reverting this and merging up #1323.

**Comment by jfly** [comment]
Before the deploy:

```
~ @production> free -hm
             total       used       free     shared    buffers     cached
Mem:          3.9G       3.7G       114M        64M        26M       176M
-/+ buffers/cache:       3.5G       316M
Swap:           0B         0B         0B
```

After the deploy:

```
~ @production> free -hm
             total       used       free     shared    buffers     cached
Mem:          3.9G       1.5G       2.4G        64M        33M       206M
-/+ buffers/cache:       1.2G       2.6G
Swap:           0B         0B         0B
~ @production> ps -ewf | grep -i unicorn
cubing   15684     1 28 00:31 ?        00:00:05 unicorn master -D -c config/unicorn.rb                                     
cubing   15738 15684  3 00:31 ?        00:00:00 unicorn worker[0] -D -c config/unicorn.rb                                  
cubing   15741 15684  4 00:31 ?        00:00:00 unicorn worker[1] -D -c config/unicorn.rb                                  
cubing   15745 15684  3 00:31 ?        00:00:00 unicorn worker[2] -D -c config/unicorn.rb                                  
cubing   15748 15684  3 00:31 ?        00:00:00 unicorn worker[3] -D -c config/unicorn.rb                                  
cubing   15801 15633  0 00:31 pts/1    00:00:00 grep -i unicorn
~ @production> 
```

**Comment by larspetrus** [comment]
Any idea what's causing the new memory problem?

**Comment by jfly** [comment]
No idea, this is just to get newrelic off our backs. Recent big and suspicious changes:

- Upgrading all the gems (https://github.com/thewca/worldcubeassociation.org/pull/1142)
- Enabling localization
- Maybe we just happened to be about perfect with our memory usage, and traffic has increased just enough to break stuff

Honestly, upgrading all the gems seems like the most likely culprit. Perhaps we have a slow memory leak now. Introducing unicorn-worker-killer would be a way to hack around that.

**Pull request merged**
