### PR TITLE
Port media approval page to Rails

### PR DESCRIPTION
**Pull request by jfly**
This has list, edit, delete, and approve functionality for media.
**NOTE**: The media submission form is still in PHP.
This is part of #296.

- Check out the new page here: https://staging.worldcubeassociation.org/media/validate
- The current PHP page here: https://staging.worldcubeassociation.org/results/admin/validate_media.php
- You can always submit more media here: https://staging.worldcubeassociation.org/results/media_insertion.php

## TODO (I'll address these in a later PR)
- [ ] Delete old PHP approval page code 
- [ ] Add a link (where?) for the WCT to actually get to this page
- [ ] Port the media submission page to RoR as well

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
Could the accept, edit, and delete buttons get moved to the right, or just made bigger? Note: I'm not sure what it currently looks like on production (I checked and there is no media to approve), so if this is a mere clone/copy, I see why it's this way (but I still prefer it gets changed).

**Comment by jfly** [comment]
> Note: I'm not sure what it currently looks like on production (I checked and there is no media to approve)

That's what staging is for =)

- Check out the new page here: https://staging.worldcubeassociation.org/media/validate
- The current PHP page here: https://staging.worldcubeassociation.org/results/admin/validate_media.php
- You can always submit more media here: https://staging.worldcubeassociation.org/results/media_insertion.php

> Could the accept, edit, and delete buttons get moved to the right, or just made bigger?

I don't love the idea of moving them right, because then as submissions get larger, the buttons move off the right side of the screen and you have to scroll horizontally to get to them.

Just making the buttons bigger also doesn't look so great:

image

How about vertical centering everything?

image

I've implemented the larger buttons with vertical middle alignment and deployed that to staging. Let me know what you think!

**Comment by FatBoyXPC** [comment]
This is definitely much better! I will say, though, that moving them to the right is fairly standard across web apps, though. That said, I do like them now!

**Comment by jfly** [comment]
> moving them to the right is fairly standard across web apps

Ok, I've made that change. We can always change it later if the WCT wants.

**Comment by jfly** [comment]
If there are no objections, I plan to merge this up tomorrow morning.

**Comment by FatBoyXPC** [comment]
I'm good with it :)

**Comment by pedrosino** [comment]
Hopefully there's time for this:

The submission date is cluttered, like 2017-10-23T04:05:23

If the "T" was not there it would look better.

**Pull request merged**
