### PR TITLE
Change solve time formatter to show multi-blind's time properly

### PR DESCRIPTION
**Pull request by Baiqiang**
Today Kaijun Lin got a 2/2 0:59 for multi-blind on Xi'an New Year 2017 (https://cubingchina.com/live/Xian-New-Year-2017#!/event/333mbf/f/all)
I found that the current formatter would format it as 2/2 59. It looks strange.

### CODE REVIEW

**Comment by jfly** [comment]
Wow, what a crazy time!

Could you update the corresponding spec file for this to test this particular case?

As far as the actual change, it looks more like "59 minutes" to me. I'd prefer 59.00.

**Comment by Baiqiang** [comment]
But in multi-blind event, we don't show the centiseconds. Would 59.00 be wired?

**Comment by Baiqiang** [comment]
I've updated the spec file.

**Comment by pedrosino** [comment]
> But in multi-blind event, we don't show the centiseconds. Would 59.00 be wired?

In fact that is wrong. See Regulation 9f:
```
9f) The results of a round are measured as follows:

    9f1) All timed results under 10 minutes are measured and truncated to the nearest hundredth of a second. All timed averages and means under 10 minutes are measured and rounded to the nearest hundredth of a second.
```

**Comment by Baiqiang** [comment]
@pedrosino Yes, the regulations say so. But the fact is we don't store the centiseconds for this event. No matter how fast the time is. You can see lots of time under 10 minutes, but none of them have centiseconds.

**Comment by pedrosino** [comment]
Indeed. We should ask delegates to change this (also maybe as @Luis-J-Ianez to update cubecomps to allow centiseconds).

**Comment by Baiqiang** [comment]
I mean, in the WCA's database, the time is stored as 0DDTTTTTMM. The TTTTT is the time in second, which doesn't contain centiseconds. It's not the issue with delegates.

**Comment by pedrosino** [comment]
Argh. Seems like we have more stuff to fix :(

**Comment by Baiqiang** [comment]
Yes. But first of all, we can change the display when time is less than 60 seconds.

**Comment by SAuroux** [comment]
Really?!

If anything, I would advocate to fix the regulations to reflect what we
have done with MBF for over 10 years. I don't really see the use of
changing lots of things for times below 10 minutes, which will be far down
in the ranking. Please keep in mind that this is the only event where high
ranked results are always in the range of 45-60 minutes, where we do not
consider centiseconds anyways.

2017-01-02 18:07 GMT+01:00 Baiqiang <notifications@github.com>:

**Comment by SAuroux** [comment]
PS: I find "0:59" for this result the most consistent.

2017-01-02 18:19 GMT+01:00 Sébastien Auroux <sebastien.auroux.sa@gmail.com>:

**Comment by jfly** [comment]
0:59 sounds good to me.

If someone wants to discuss storing centiseconds for multi, please start a separate discussion for that. However, I am with Sébastien, and would rather see the regulations changed.

**Comment by jfly** [comment]
LGTM! Thanks for writing the test =)

@Baiqiang, since you're a member of the software team, can you merge this up yourself? Instructions here: https://github.com/thewca/worldcubeassociation.org/wiki/Merging-and-deploying#policy-for-merging-code

**Pull request merged**
