### PR TITLE
Cache ranking pages

### PR DESCRIPTION
**Pull request by jonatanklosko**
This uses the standard view caching, but given we do plain SQL queries, I moved the actual `exec_query` to the view file. Let me know what you think of that approach =)

### CODE REVIEW

**Comment by jonatanklosko** [comment]
That's to avoid running the SQL queries in controller when we are going to serve cached rankings. With ActiveRecord if you do stuff like `@competitions = Competition.where(...)` then no query is executed until you actually use `@competitions` in the view. Here we directly use `exec_query`, so we need to ensure it's fired only if necessary ourselves.

**Comment by viroulep** [comment]
To complete what Jonatan explained: that's definitely a temporary workaround until we move these queries to plain rails.
As you mentioned @maconard having logic in the views files is definitely not something we're looking for :D

**Comment by viroulep** [comment]
Superseded by #4483.
I've rebased this PR there!

**Comment by viroulep** [comment]
Thanks a whole lot Jonatan, the server looks much better now!

**Pull request closed without merging**
