### PR TITLE
Flatten markdown before putting into schedule

### LINKED ISSUE #3634: Markdown issues in the schedule tool
The name of the venue does not support markdown in the schedule tool. This makes every single schedule (for a competition which uses markdown for the venue's website) look like this by default and it is rather rare that a Delegate fixes this: 
image
This is such a minor mistake which is very commonly recurring, but looks awful, so the WCAT has to fix this for the Delegate for 50% of all submissions, which adds up to some time to correct it. 

Would it be possible to get the website to ignore the URL part of the venue name so it doesn't include the link when adding the venue to the schedule?

### PR DESCRIPTION
**Pull request by UnsolvedCypher**
Fixes #3634 by creating an new helper function to flatten markdown into plaintext before putting it into the schedule view.

### CODE REVIEW

**Comment by viroulep** [comment]
Naive question: what's wrong with using the existing `md` helper?

(potential follow-up: if there *is* something wrong, is this something we could fix by passing a parameter to the existing function?)

**Comment by UnsolvedCypher** [comment]
The existing md helper wraps everything in <p> tags. Also, it preserves links which we do not want in this case. This can't be solved by passing parameters, but if you prefer, I could add a new optional parameter to the excluding function.

**Comment by viroulep** [comment]
Ok I initially missed your point of stripping links!

I look into this a bit because I was not convinced about the overall raw text -> html -> raw text process, and I think I've come up with something "cleaner".
We can define another custom renderer that just don't output links and paragraph:

```ruby
  class RawTextRenderer < Redcarpet::Render::HTML
    def link(link, title, content)
      content
    end
    def paragraph(text)
      text
    end
  end
```
(you can define this right after `WcaMarkdownRenderer` line 49; I did try using the `StripDown` renderer described [here](https://github.com/vmg/redcarpet/blob/master/README.markdown#darling-i-packed-you-a-couple-renderers-for-lunch), but it doesn't quite do what we want)

Then you can define a `md_as_text` helper as simple as:
```ruby
  def md_as_text(content)
    Redcarpet::Markdown.new(RawTextRenderer.new(filter_html: true)).render(content)
  end
```

If we ever need to strip down more stuff we can still extend the `RawTextRenderer`.

Also please make sure to define the helper *within* the `module MarkdownHelper`, which I believe is not the case currently.

**Comment by UnsolvedCypher** [comment]
@viroulep Thank you for these suggestions, that does indeed seem cleaner :)

**Comment by UnsolvedCypher** [comment]
Ok, looking further into this, it appears that this issue occurs in some other places, not just as the title of the schedule. I think the ideal solution would be to flatten it to text before it's passed into React, which would be [right here](https://github.com/thewca/worldcubeassociation.org/blob/0e26dd828a7c22644b5ce0b37674f6fa2f63851b/WcaOnRails/app/views/competitions/edit_schedule.html.erb#L12). Does that seem like a good approach? Or, the flattening could also be done in JavaScript once React actually has the information.

**Comment by AlbertoPdRF** [comment]
What's the status of this PR? It's not totally clear to me if it requires further changes or if it can be merged as is.

**Comment by viroulep** [comment]
Hum I think @UnsolvedCypher made a very good point earlier that flattening the markdown before passing it to react would be very helpful, I think we should do that.

@jfly 
> @UnsolvedCypher, could you give some more information about what's wrong with the venueDetails containing markdown?

I missed replying to that.
The thing is, `venueDetails` *can* contain markdown, but this is just some text passed to react to be used as a default venue *name* in the WCIF. Since the WCIF contains both the venue name and the coordinates I don't think we need a url (we actually craft a link from coordinates + name).

For the competition itself, it's very fine to keep the markdown in there.

**Comment by jfly** [comment]
Got it. A few more questions, then:

- Why do we pass `venueDetails` instead of `venue` into react here? https://github.com/thewca/worldcubeassociation.org/blob/70649f97e55e0d618b4ba223b11f84985f231262/WcaOnRails/app/javascript/edit-schedule/EditVenue/index.jsx#L162
- How do we feel about changing `venue` to not support markdown. This will force users to specify plain text for the venue names, and then it would make sense in the schedule.

This also probably isn't worth agonizing over too much. Long term, I imagine us eventually removing the `venue` and `venueDetails` fields from the `Competitions` table in favor of actually forcing competition creators to deal explicitly with each venue of the competition (to handle FMC simultaneous competitions nicely).

**Comment by AlbertoPdRF** [comment]
> This also probably isn't worth agonizing over too much. Long term, I imagine us eventually removing the `venue` and `venueDetails` fields from the `Competitions` table in favor of actually forcing competition creators to deal explicitly with each venue of the competition (to handle FMC simultaneous competitions nicely).

Should we then move forward with this PR flattening the markdown before passing it to react, and opening an issue (assuming there isn't one already) to keep track of the long-term plans?

**Comment by jfly** [comment]
I would prefer to do one of the 2 ideas I proposed in https://github.com/thewca/worldcubeassociation.org/pull/3656#issuecomment-518105791, but would also like to see what @viroulep thinks first.

**Comment by Jambrose777** [comment]
I had this on the list of bugs I wanted to fix and realized there was a PR on it that's been sitting 2 years.

> * How do we feel about changing `venue` to not support markdown. This will force users to specify plain text for the venue names, and then it would make sense in the schedule.

I wanted to answer this question. There are ~4000 competitions out of ~7500 that use the markdown feature in the venue field. So even with it being possible to strip this out via a script/sql, I think most Delegates/Organizers appreciate this feature and would like to keep it around given how many use it.

> Why do we pass venueDetails instead of venue into react here?

I believe this is because most people put room names in venue details (and if it's wrong they are freely able to change it). But a competition might have `venue: Classic City Center` and `venue details: Grand Hall A-C` so it would autopopulate with the thing most likely resembling a room name instead of the venue name twice.

For the rest of the conversation for extra things it looks like this can be taken care of in a new feature for multiple venues. I made a new issue to track the want for this #5988.

If I'm not mistaken the consensus points to [this solution](https://github.com/thewca/worldcubeassociation.org/pull/3656#issuecomment-448752690). which will move the md_as_text use to the react import portion. @UnsolvedCypher are you still able to do this here?

**Comment by jonatanklosko** [comment]
I'm going to close this due to inactivity, feel free to reopen/resubmit when you are able to continue working on this.

**Pull request closed without merging**
