### PR TITLE
Improve responsive design of Events and Schedule tables

### PR DESCRIPTION
**Pull request by dunkOnIT**
Some complaints have related to the way the new Table view is formatted on mobile - `unstackable` property may solve this

### CODE REVIEW

**Comment by dunkOnIT** [comment]
@thewca-bot deploy-staging

**Comment by dunkOnIT** [comment]
@thewca-bot deploy staging

**Comment by dunkOnIT** [comment]
@gregorbg have added scrollability! Didn't seem to break it on mobile, but it was impossible to navigate on desktop.

This PR is now ready for review, the `unstackable` option is definitely preferred by people who are quite vocally against the current view

**Comment by dunkOnIT** [comment]
@thewca-bot deploy staging

**Comment by gregorbg** [comment]
At least for the Events table, you should consider including `singleLine` in addition to `unstackable`. This replicates the previous behaviour from before the migration.

**Comment by gregorbg** [comment]
I took the liberty of reimplementing the old responsive behaviour of the schedule table

**Comment by gregorbg** [comment]
@thewca-bot deploy staging

**Comment by gregorbg** [comment]
@thewca-bot deploy staging

**Comment by gregorbg** [comment]
@thewca-bot deploy staging

**Review by kr-matthews — APPROVED** [review]

**Pull request merged**
