### PR TITLE
Update Traditional Chinese listing on Regs translations page.

### PR DESCRIPTION
**Pull request by lgarron**

### CODE REVIEW

**Comment by kotarot** [comment]
@jonatanklosko @lgarron 

@hanwu85 noticed and said at the competition today, but the regulations are not built yet? In the translation page, it seems that the latest commit hash points to https://github.com/thewca/wca-regulations-translations/commits/c0ca133 and it is not updated to the latest version.

スクリーンショット 2019-09-21 18 36 39

**Comment by jonatanklosko** [comment]
Whoops, done!

**Comment by kotarot** [comment]
Thank you so much!

**Comment by hanwu85** [comment]
Thank you all~!

**Pull request merged**
