### PR TITLE
Fix translation de result typo

### PR DESCRIPTION
**Pull request by KiwiKilian**

### CODE REVIEW

**Comment by jonatanklosko** [comment]
Hey Kilian, thanks for submitting the pull request! We have a dedicated software for translating the website and changes to translations need to be introduced via that software, otherwise it will be ambiguous which version is the correct one.

@Laura-O could you make this fix in Internationalize and submit an update then?

**Comment by KiwiKilian** [comment]
Hey Jonatan,
I read [the translation guide](https://github.com/thewca/worldcubeassociation.org/wiki/Translating-the-website#general-notes) where it says:

> If you know how to submit a pull-request (PR), feel free to do so :) Here is an example of such PR.

Maybe you guys want to update, when to use the tool or directly send PRs. Cheers! :)

**Comment by Laura-O** [comment]
> @Laura-O could you make this fix in Internationalize and submit an update then?

Yep, I will update the translation soon and fix the typo.

**Comment by jonatanklosko** [comment]
@KiwiKilian The file in the PR you referenced is actually generated by the tool. To be more precise, the real problem is not even using the tool or not, but multiple sources of truth. We kinda assume that every translation is handled by a single person (or many people with a shared account in the tool), otherwise it gets out of sync ^^ It's definitely not perfect, but this assumption works fine most of the time.

@Laura-O thanks!

**Pull request closed without merging**
