### PR TITLE
Add more localized translations of Chinese

### PR DESCRIPTION
**Pull request by Nthily**

### CODE REVIEW

**Comment by Nthily** [comment]
Translated a lot of content, now the progress is 1153/1589.
if the reviewer see this pr can be directly merged, the subsequent new translation I will additionally submit a new pr :)

**Comment by hanwu85** [comment]
Hi,

Thank you for the update.
Have you talked to the WST?
Actually this is not how official translation flow works, it is not wrong though.

You can see the flow works here.
https://github.com/thewca/worldcubeassociation.org/wiki/Translating-the-website

Let's see what the WST think about this.

**Comment by Nthily** [comment]
> Hi,
> 
> Thank you for the update. Have you talked to the WST? Actually this is not how official translation flow works, it is not wrong though.
> 
> You can see the flow works here. https://github.com/thewca/worldcubeassociation.org/wiki/Translating-the-website
> 
> Let's see what the WST think about this.

I haven't talked to WST yet, but I followed the steps on the wiki to get it done.

I used the [Internationalize app](https://internationalize.herokuapp.com/) by Jonatan Kłosko for the translation, and finally downloaded the translated zh-CN.yml file to replace the original.

**Comment by hanwu85** [comment]
You should upload the translation here https://www.worldcubeassociation.org/translations
not directly to github.  It is stated in the wiki.

But I think if you get the file from the Internationalize app, it is alright.
I think the reason why we use https://www.worldcubeassociation.org/translations is to verify the translator and they have to have a WCA account.
Like this one https://github.com/thewca/worldcubeassociation.org/pull/6812
Let's see what they think about it.
If you have the file you can still upload it via the website anytime.

**Comment by Nthily** [comment]
@hanwu85 ok I see, thanks for your help, but the wiki does say you can submit pr directly.
[here](https://github.com/thewca/worldcubeassociation.org/wiki/Translating-the-website#general-) notes)
> If you know how to submit a pull-request (PR), feel free to do so :) [Here](https://github.com/thewca/worldcubeassociation.org/pull/1105) is an example of such PR.

I just resubmitted a [pr](https://github.com/thewca/worldcubeassociation.org/pull/6816) on the WCA website.

**Comment by notrichardpeng** [comment]
Hey, thank you very much for your work! The translations look pretty good, and I merged the PR.

**Comment by Nthily** [comment]
@notrichardpeng thank you! Can I resubmit a pr to update `WcaOnRails/config/locales/carrierwave.zh-CN.yml`? Because it seems that this file cannot be submitted from the WCA website

**Comment by notrichardpeng** [comment]
yeah sure! Let me know if you encounter any problems

**Pull request closed without merging**
