### PR TITLE
Gender Rankings Added

### LINKED ISSUE #168: Gender stats
In September, 2017, the WCA delegates were asked "Should the WCA website allow filtering rankings by gender?" The results of the poll were 84 yes and 31 no.

There are a few issues related to this. See:

- https://groups.google.com/forum/#!msg/wca-delegates/lhY0MsfN-rw/OGjWHVFaAgAJ - Relevant discussion on the WCA delegates list
- https://github.com/cubing/wca-regulations/issues/160 - Relevant WRC issue on this topic
- https://github.com/thewca/worldcubeassociation.org/issues/301 - Port events.php to Rails
- https://github.com/thewca/worldcubeassociation.org/issues/1919 - Change the way records are displayed on events.php

There is some uncertainty about how we want to handle people with gender `o`. Either we allow filtering by "male, female, or other", or we only allow filtering by "male or female".

### PR DESCRIPTION
**Pull request by Jambrose777**
Fixes #168. Added Gender Rankings on Rankings page.

image

Notes:
- I couldn't find any test for the result_controller. I'd be happy to add tests for the specific gender logic, but I'm not sure which tests files if any that these would go in.
- I only have filters for Male/Female. It was discussed a little on the issue, but due to the sensitivity around 'other' as well as if people want to be excluded from gender rankings they've changed their gender to other, I felt it best to not have that be a filter.
- I also did some work adding gender rankings to the RanksSingle/Average tables. I found out after that these are not used on the rankings page, but rather the person profiles. If we ever want the rankings to appear on personal profiles, that branch would be an excellent starting point with the db changes and CAD computing the rankings: https://github.com/thewca/worldcubeassociation.org/compare/master...Jambrose777:gender-rankings-db-and-cad-changes

### CODE REVIEW

**Comment by maconard** [comment]
Looks nice. Do you think the gender selector would make more sense between the year and quantity selectors, though? I guess in my mind, the amount of results returned selector is like the final decision, and thus at the far right.

**Review by jonatanklosko — COMMENTED** [review]
The implementation looks very clean, thanks! I agree with @maconard in terms of the UI.

> I couldn't find any test for the result_controller. I'd be happy to add tests for the specific gender logic, but I'm not sure which tests files if any that these would go in.

The rankings have been ported to Rails by Alberto and there actually are no relevant tests. [This](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/spec/requests/results_spec.rb) is the proper file, but as you can see it only tests some basic redirects at this point. I think we don't test the read-only parts much, rather those that involve data mutation and access (but feel free to play around with it if you like!).

Also, the voting results are from 3 years and this is quite a sensitive topic (I guess), so perhaps the Board should formally approve this?

**Comment by Jambrose777** [comment]
Sure thing! Here is the new one:
image

I agree that the @thewca/board can have a look and see if other actions need to be taken.

**Comment by cubewhiz** [comment]
The Board will discuss this at our next meeting (on Sunday, Oct. 25)

**Comment by saranshgrover** [comment]
Board has discussed and is okay with this. Please feel free to proceed @Jambrose777

**Comment by jonatanklosko** [comment]
I believe this is ready to go, @Jambrose777 is that correct?

**Comment by Jambrose777** [comment]
> I believe this is ready to go, @Jambrose777 is that correct?

Correct!!

**Pull request merged**
