### PR TITLE
Bundle all Ruby constant exports to Webpacker in one file

### PR DESCRIPTION
**Pull request by gregorbg**
...so that staging doesn't die trying to spin up 12 servers in parallel.

Temporary solution to the symptoms discussed in #7284. Not beautiful, but necessary.

### CODE REVIEW

**Comment by FinnIckler** [comment]
Sounds like a good solution for now, I mean our goal is to have 0 .js.erb files in the end right?

**Comment by gregorbg** [comment]
Yes, that would be the end goal. The current PR is a step along the way.

**Review by jonatanklosko — APPROVED** [review]
Looks like a good workaround!

FWIW I think it's actually better to have a single ~100 loc file with the "bridge" stuff, rather than a bunch of ~10 loc files :)

**Comment by gregorbg** [comment]
Thanks! :smile:

**Pull request merged**
