### PR TITLE
Allow qualification on the day of the deadline

### PR DESCRIPTION
**Pull request by gregorbg**
As per WRT remark. This PR merely swaps a `<` comparison for a `<=` comparison

### CODE REVIEW

**Review by dunkOnIT — DISMISSED** [review]
Edit: Oops, only checked diff not tests
LGTM

**Comment by dunkOnIT** [comment]
@gregorbg we may want to add test cases for `on_or_before` in addition to the `before` tests? Or just update the expectation of the old tests, I haven't looked in detail at which is more appropriate

**Review by dunkOnIT — APPROVED** [review]

**Comment by FinnIckler** [comment]
Isn't this V1?

**Comment by dunkOnIT** [comment]
I believe v2 is just calling the qualification class to check qualifications, so it should still apply

**Comment by timreyn** [comment]
Can you also update the text on https://www.worldcubeassociation.org/competitions/WC2025#competition-events ? Under "Qualification" it says "by DATE_MINUS_ONE", and at the bottom it says "before".

Thank you!

**Pull request merged**
