### PR TITLE
Add route for full.html.erb regulations

### PR DESCRIPTION
**Pull request by Nanush7**
See https://github.com/thewca/wca-regulations/pull/1199 and https://github.com/thewca/wca-regulations-compiler/pull/28.

### CODE REVIEW

**Comment by gregorbg** [comment]
The files are now hosted on S3, yay!

**Review by gregorbg — APPROVED** [review]
Fine with the change as-is, you might want to add a dropdown menu option so that users can actually navigate to the new file?

Code is at `app/views/layouts/_navigation.html.erb` somewhere around line 80-ish

**Comment by Nanush7** [comment]
Yes! We want that :)

Any ideas for the icon?

**Comment by gregorbg** [comment]
Be my guest: https://fontawesome.com/v4/icons/

My spontanenous suggestions: `cc`, `support`, `plus square`

**Comment by Nanush7** [comment]
What about [plus-square](https://fontawesome.com/v4/icon/plus-square) for the Guidelines, [file-text](https://fontawesome.com/v4/icon/file-text) (this one is used in the information dropdown menu too) for the Regulations and leave the current `book` for the full version?

For the text, does "Regulations & Guidelines" look good?

**Comment by gregorbg** [comment]
> What about [plus-square](https://fontawesome.com/v4/icon/plus-square) for the Guidelines, [file-text](https://fontawesome.com/v4/icon/file-text) (this one is used in the information dropdown menu too) for the Regulations and leave the current `book` for the full version?
> 
> For the text, does "Regulations & Guidelines" look good?

Quite honestly, I'm not the person to make this decision. I only have the authority over technical implementation details, but the community (or at least the WRC) should be the one to make this design decision.

**Comment by Nanush7** [comment]
@gregorbg Done!

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
