### PR TITLE
Change 100% volunteer references

### PR DESCRIPTION
**Pull request by dunkOnIT**
Addresses #7917

### CODE REVIEW

**Comment by gregorbg** [comment]
This should be approved by the WCA Board.

**Comment by dunkOnIT** [comment]
Cool - my suggestion is to include it for approval in the next Report? Shout if you want me to raise it with them sooner.

**Comment by gregorbg** [comment]
Shout! No need to glue this into the report, just send them a separate email.
Increases our chance of getting an earlier reply.

**Comment by dunkOnIT** [comment]
Shout acknowledged :P Just confirming you're aware it has already been approved by WCT in "Wording of "100% Volunteer" References"?

**Comment by gregorbg** [comment]
Thanks for the reminder, but actually WCT may not be able to evaluate legal consequences this may or may not have for our non-profit status.

I may be hugely overcomplicating things here, but better be safe than sorry.

**Review by KerrieJarman — APPROVED** [review]
Confirmed with other Board members, all good

**Pull request merged**
