### PR TITLE
Adjust displayed fee based on selected events - Fixes #1674

### LINKED ISSUE #1674: Registration fee should be dynamically adjusted based on per event fees
The database schema now supports per event fees, and as such the registration UI should dynamically update the current fee as a competitor selects, or deselects events on the registration page.

### PR DESCRIPTION
**Pull request by pingskills**
I'm not sure if this is the best way to go about this feature. There is one big issue in that I don't know how to use the Money class from within Javascript to display the fee in the required format with the correct currency. At the moment I'm just displaying the lowest denomination amount as you can see in the image below:
dynamic-fees

Any thoughts or suggestions on this would be appreciated. Also, if someone gets inspired and has a better way to do this I'm more than happy to remove this PR :)

### CODE REVIEW

**Comment by jfly** [comment]
Also, after we merge this up, do we have an issue to track adding support for setting event prices somewhere? That data still only exists in our database, right?

**Comment by pingskills** [comment]
Hi @jfly that does sound like a cleaner approach. Do we have any good examples to follow in the current code base?

I don't think we do have an issue for setting the prices. I'll add that now.

**Comment by jfly** [comment]
> Do we have any good examples to follow in the current code base?

Yes, we do some of this on the [competition edit page](https://staging.worldcubeassociation.org/competitions/new), specifically the "time until competition" field:

image

Relevant code here:

- js code to initiate update: https://github.com/jfly/worldcubeassociation.org/blob/8fdd5f69d151fcdc401fe3e0d9ec37b0d3f1c883/WcaOnRails/app/views/competitions/_competition_form.html.erb#L137-L148
- route: https://github.com/jfly/worldcubeassociation.org/blob/8fdd5f69d151fcdc401fe3e0d9ec37b0d3f1c883/WcaOnRails/config/routes.rb#L63
- controller action: https://github.com/jfly/worldcubeassociation.org/blob/8fdd5f69d151fcdc401fe3e0d9ec37b0d3f1c883/WcaOnRails/app/controllers/competitions_controller.rb#L416-L424
- erb partial: https://github.com/jfly/worldcubeassociation.org/blob/master/WcaOnRails/app/views/competitions/_time_until_competition.html.erb

**Comment by jfly** [comment]
@pingskills, quick ping here. Do you have any time to push this over the finish line?

**Comment by pingskills** [comment]
@jfly Yeah I should get some time early next week. Sorry I've left this one for a while.

**Comment by pingskills** [comment]
I created a new branch for the new approach #2536 so I'm going to close this pull request.

**Pull request closed without merging**
