### PR TITLE
Added translation for 3x3x3 MBLD (old-style) in time limit under events tab

### PR DESCRIPTION
**Pull request by chesspatzer**
Added the missing translation for old style mbld time limit

### CODE REVIEW

**Review by jonatanklosko — COMMENTED** [review]
Hey @chesspatzer, sorry for the delay.

One important detail about the translation files is that we should only touch `en.yml` directly. It serves as a source of truth in terms of what phrases are currently used. Then we have a group of translators who get notified about changes to `en.yml` and they update the relevant translations in a dedicated Internationalize app and submit PRs via form on the website. Among other things the app generates the necessary `#original_hash` annotations, and editing the files directly on GitHub causes problems.

So please update the PR to fix `en.yml` and we should be good =)

**Comment by viroulep** [comment]
We didn't notice this but when discussing about the website with @denthebro we ended up reworking his work in #6304 to simply edit `en.yml` in a similar fashion to what was suggested by @chesspatzer.

**Comment by denthebro** [comment]
@viroulep thank you. I think both of these issues can be closed and the PR merged

**Comment by Jambrose777** [comment]
Closing as #6304 was merged.

**Pull request closed without merging**
