### PR TITLE
Friday Gemday!

### PR DESCRIPTION
**Pull request by jfly**
- Update (almost*) all gems via bundle update.
- Update all yarn deps via `bin/yarn upgrade`

\* **NOTE: I didn't update webpacker (#1901) or rails-assets-autoNumeric (#1900).**

### CODE REVIEW

**Comment by greysteil** [comment]
Would you be up for automating creating dependency update PRs? I built [Dependabot](https://dependabot.com) at my last company to automatically create PRs whenever a new dependency version is released, and it's totally free for open-source. Could be a timesaver?

**Comment by jfly** [comment]
@greysteil, Dependatbot looks very cool! I looked into setting it up, but am confused it why it needs write access to our code. Can you give any insight into that?

image

**Comment by greysteil** [comment]
Yeah, it's a pain, but we decided it was better to ask for write access than to work on repo forks (particularly with private repos). Given that setup, Dependabot needs write access because it creates a new branch on your repo for each PR.

We set Dependabot up to never, ever push to your master or default branches, and went as far as putting it in the product's [terms of service](https://dependabot.com/terms.html) (last sentence in the second paragraph of "Service specification"). It'll only ever push to branches namespaced under `dependabot/`

**Comment by jfly** [comment]
Ok, I just tried setting up Dependabot for `thewca/worldcubeassociation.org`. We'll see how it goes =)

**Comment by greysteil** [comment]
Awesome! I literally just updated it to be using Bundler 1.16.0.pre.1 (I helped with some of the updates in that version, so want to help out with testing), so if you see anything fishy with the first set of PRs it generates let me know!

**Pull request merged**
