### PR TITLE
Export delegates

### PR DESCRIPTION
**Pull request by Baiqiang**
Currently there's no easy way to get a delegate's competitions via the public export or the api.

### CODE REVIEW

**Comment by Baiqiang** [comment]
Last year I implemented personal summary on Cubing China. [Danyang Chen](https://www.worldcubeassociation.org/persons/2007DANY01) said he delegated many competitions but didn't join in one.  The 2016's summary page for him is almost blank: https://cubingchina.com/summary/2016/2007DANY01. That's another reason I want this to be exported.

**Comment by jfly** [comment]
LOL I'm  loving the text on https://cubingchina.com/summary/2016/2007DANY01:

image

**Comment by jfly** [comment]
@Baiqiang, would you be open to consuming the [developers database export](https://www.worldcubeassociation.org/wst/wca-developer-database-dump.zip) instead?

Maintaining this public export is a pain for the WST, because every database migration potentially breaks it (for example, this code you wrote is going to break when @pedrosino merges #2027), and we don't have any tests of it. Also, every feature we add here in PHP makes it that much harder to port this to RoR.

**Comment by Baiqiang** [comment]
@jfly Sorry I didn't realize the database structure will be changed soon.
The developers database export is a little big and I have to import it and then get what I need. It's not so convenient.
Can we extend the api to support querying a delegate's competitions? Or write a new one to returned competition IDs only.
And it will be better if the results limit can be specified.

**Comment by jfly** [comment]
> The developers database export is a little big and I have to import it and then get what I need. It's not so convenient.

If we keep adding things to the public database export, it will eventually become just as big as the developer export =)

> Can we extend the api to support querying a delegate's competitions?

Sure! We do actually have the `managed_by_me` parameter for the `/api/v0/competitions` route: https://github.com/jfly/worldcubeassociation.org/blob/7baecc2c19cc42c63e9b3ad76187e5987a491bad/WcaOnRails/app/controllers/api/v0/competitions_controller.rb#L6, but that's only useful for when you've had people log into your website. It could make sense to add a `managed_by` url parameter that takes a user id and returns all the competitions they manage (you'd have to take care to only return visible competitions, though).

**Comment by Baiqiang** [comment]
I'm going to close since we should find another solution instead of adding content to the export endlessly.

**Pull request closed without merging**
