### PR TITLE
Adding endpoint to query for @Logiqx's anonymous age rankings.

### PR DESCRIPTION
**Pull request by jfly**
@Logiqx gave me this query. I munged it a bit, but someone should take a closer look at it before we merge it up.

I didn't try too hard to write a very interesting test, I just wrote a pretty simple smoke test.

### CODE REVIEW

**Comment by Logiqx** [comment]
Thanks @jfly. I wasn't expecting you to create a PR but very much appreciate your time and effort.

I've had a quick glance at the code and there is one small glitch relating to the re-factoring. The join clause average >0 should be changed to #{column_name} > 0.

If the WDPC are happy with this to be implemented it would be fantastic from my perspective. I can easily make use of this endpoint during the daily refresh of https://logiqx.github.io/wca-ipy-www/Senior_Rankings.html

**Comment by Logiqx** [comment]
Additional comments:

@jfly used SQL from https://github.com/Logiqx/wca-ipy/blob/master/sql/extract_senior_groups.sql

This is the same SQL as per the extract on 20 Dec 2019.

**Comment by Logiqx** [comment]
@viroulep - I believe it takes about 3-4 seconds to run against the WCA database.

This was the query that was finally accepted after a number of earlier proposals but I am making no assumptions about whether it is acceptable for an endpoint. I'd like to think it would be but it clearly needs to go through the WDPC.

If the endpoint is implemented then I'd look to use it once a day, during my refresh of the senior rankings shortly after 0410 UTC.

**Comment by Logiqx** [comment]
Further to my comment about the run time of 3-4 seconds you may have noticed a query hint (avoiding indices on the Persons table) because the query optimiser is liable to come up with a poor execution plan when left to its own devices.

The full scan of the Persons table is immediately reduced to ~2000 seniors by the "where clause", facilitating an efficient join to Results and Competitions tables using the appropriate indices. I don't recall the query plan of MySQL when choosing from the WCA indices but it was something quite daft and a lot slower.

The query hint ensures the query runs as intended in 3-4 seconds.

**Comment by Logiqx** [comment]
I just checked and when I originally wrote the core of that query the WCA was still on MySQL 5.x.

The optimiser does the right thing in MySQL 8.x so there is no longer a requirement for the query hint.

**Comment by Logiqx** [comment]
> A few things that came up to my mind while reading through the PR:
> 
> * I heavily dislike the raw SQL in the middle of the controller :s. We already have a lot of it in the results one (which I understand we tolerate because it's a direct port from php), but I'd rather avoid bringing more into the codebase.
>   Especially the select into select into select makes me think we could just query the main set of persons/results and do some filtering over it in rails.

@jfly - I've looked at the SQL and it can be greatly simplified if rails does some post-processing. The SQL snippet below can be run for each age category and post-processing in rails can calculate averages of every 6 records.

```
SELECT eventId, MIN(#{column_name}) AS best
FROM Persons AS p
JOIN Results AS r ON r.personId = p.id
JOIN Competitions AS c ON c.id = r.competitionId
WHERE p.year > 0 AND p.year <= YEAR(CURDATE()) - #{age_category}
AND subid = 1
AND #{column_name} > 0
AND TIMESTAMPDIFF(YEAR, DATE_FORMAT(CONCAT(p.year, '-', p.month, '-', p.day), '%Y-%m-%d'), start_date) >= #{age_category}
GROUP BY eventId, personId
ORDER BY eventId, best
```

Performance wise it doesn't take any longer to run this SQL multiple for each age category but it would result in a cleaner code-base. The size of the result set is well within what I'd consider sensible for post-processing in rails.

I've added the above SQL snippet and some comments about the post-processing to the original extract - https://github.com/Logiqx/wca-ipy/blob/master/sql/extract_senior_groups.sql

**Comment by jonatanklosko** [comment]
I'm going to close this due to inactivity.

**Pull request closed without merging**
