### PR TITLE
Request spectator info in information section

### PR DESCRIPTION
**Pull request by UnsolvedCypher**
The WCT receives a lot of emails asking for spectator information about competitions. I think this would be a good reminder for organizers/delegates to put that in the information section.

### CODE REVIEW

**Comment by jfly** [comment]
Looks good! Maybe add a parenthetical with examples of some questions that potential spectators like to ask?

Thanks for sending in a PR :) should the WST assume the WCT has discussed and is pleased with this change?

**Comment by UnsolvedCypher** [comment]
I've edited the file again to add some more details. The WCT is happy with this change :)

**Comment by SAuroux** [comment]
This is weird and kind of arbitrary. The previous text was one very general sentence. The new text is two sentences with one very general sentence and one specific sentence about spectator information.

**Comment by jfly** [comment]
@SAuroux, the first sentence has a very specific example of what one could put in this field "e.g., Euro 2006 is open to citizens of the European countries and Israel", would you be happier if @UnsolvedCypher moves his addition into that parenthetical?

If not, could you suggest something to try to improve the problem that the WCT "receives a lot of emails asking for spectator information about competitions"?

**Comment by Laura-O** [comment]
I agree that this is a very specific addition, which is quite selective. However, the current example is quite bad as well. :stuck_out_tongue_winking_eye:
Why not change it to something like this:
"Information about competitor limit, entry fees for competitors and spectators and other details".

**Comment by SAuroux** [comment]
I like Lauras suggestion. I would slightly extend it to this:

"Information about competitor limit, entry fees for competitors and spectators and other details particularly relavant for people interested to register."

By the way, that Euro 2006 example is outdated anyways, since competitions are generally open for anyone these days. :)

**Comment by UnsolvedCypher** [comment]
I also really like that idea. I have changed it to "Information about the competitor limit, entry fees for competitors and spectators, and other details particularly relevant for people interested in competing or spectating." Does that sound good?

**Comment by SAuroux** [comment]
Yes, sounds good to me. :)

**Comment by jonatanklosko** [comment]
Nit: 4 commits changing one sentence seems kinda weird to me.

**Comment by UnsolvedCypher** [comment]
@jonatanklosko Agreed - I can make a new pull request with the final commit so that we're not merging 3 pointless commits in, would you like me to do that?

**Comment by jonatanklosko** [comment]
@UnsolvedCypher Yessir, please!

**Comment by jfly** [comment]
No need for a new PR, though! Just update the existing one with some git-foo =)

**Comment by jonatanklosko** [comment]
Bump, I've seen you had closed the PR, what's the state of the change =) ?

**Comment by UnsolvedCypher** [comment]
Sorry for the delay. I've done some git magic to turn the commit into one, so if everyone is still on board with this, it should be ready to merge.

@jonatanklosko: I made a new PR just as I saw @jfly suggest git-foo instead, so I closed that pull request immediately and fixed this one - sorry for the confusion

**Comment by jonatanklosko** [comment]
Great, thanks =)

**Pull request merged**
