### PR TITLE
Added confirmation in probation page and sending email for changes

### PR DESCRIPTION
**Pull request by danieljames-dj**

### CODE REVIEW

**Review by gregorbg — COMMENTED** [review]
Are there end-to-end tests for the Probation UI?
If so, can you please change those so that they expect the "send email" method to be called?

**Comment by danieljames-dj** [comment]
> Are there end-to-end tests for the Probation UI? If so, can you please change those so that they expect the "send email" method to be called?

Yes, there is. I've added it now.

**Comment by gregorbg** [comment]
This needs a rebase now

**Comment by danieljames-dj** [comment]
> This needs a rebase now

Done.

**Review by gregorbg — APPROVED** [review]

**Pull request merged**
