### PR TITLE
Warn new registrant once a competitor limit is reached

### LINKED ISSUE #2584: Show if competition is full on registration page
I really think this would be useful. For my competition, even though it is full, plenty of users are signing up, and they are currently on the 20 user waitlist that I specified prior to registration. They will be approved if another competitor drops out.

However, I feel like for some of the newer/younger cubers who are unfamiliar to the system, particularly ones who are signing up with their parents, they might not know that the competition is full because they didn't check the registration list.

So, I'm thinking it would be useful to have something on the registration page, along the lines of:

"The competitor limit for this competition is X. This competition is currently at the competitor limit. If you are signing up then your registration will be placed on a waiting list, that the organizer has specified."

I think this would make things clearer for newer cubers who are not familiar with the WCA registration system.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #2584.

Limit hasn't been reached:

image

Limit has been reached:

image

@Z4chy thoughts?

### CODE REVIEW

**Comment by viroulep** [comment]
Great, LGTM :)
(weird tests failures though, the incident log one could probably be solved by forcing an order on the array, my bad...)

**Comment by jonatanklosko** [comment]
@viroulep weird errors indeed, I changed `eq` to `match_array`, so it should be fine now. Let' see =)

**Comment by Z4chy** [comment]
Looks great :) :D

**Comment by jonatanklosko** [comment]
@Z4chy oh wow, I forgot to wait for your opinion before merging, glad you like it =)

**Comment by viroulep** [comment]
He actually liked it in the fixed issue before you merged the PR :)

**Comment by jfly** [comment]
This is super awesome, thanks @jonatanklosko!

**Pull request merged**
