### PR TITLE
Add scrambles view and api endpoint

### LINKED ISSUE #65: View scrambles
We've been uploading scrambles for over a year now, and the only way to view them is by downloading a database export! Maybe we can make them viewable on the web within a year =)

### PR DESCRIPTION
**Pull request by zeecho**
Closes #65 

This is highly based on the "all results" view. Among other things, it re-uses the events navbar and adds two api endpoints (/:competition/scrambles and /:competition/scrambles/:event (only the last one is used for the view but the other one could be useful for other people)).

Note: when we'll update cubing-icon, the "match-the-scramble" icon should appear on the left menu (like for the results)

Here are a few screenshots: 
2021-02-16-145851_950x932_scrot
2021-02-16-145947_1280x952_scrot

Thanks a lot to @viroulep for his help and for pre-checking this PR ;)

### CODE REVIEW

**Comment by viroulep** [comment]
For the record I took a shot at including a newer version of cubing icons through webpacker (and deleting the one we used in `vendor/assets`).
Overall it went well, but there was an issue in the pdf layout used for displaying competition's events/schedule as pdf: wicked_pdf doesn't support packs with chunks and the only way I found to make it work was to add a specific node_modules path to rails' assets paths.
If that's too dirty I'd suggest to just update our vendor/assets to the latest cubing icons and not include it through webpacker.

Here is what it looks like with the working icon:
scrambles

Also for the record I already reviewed @zeecho's code before he sent the PR and it looked good to me!

**Review by jonatanklosko — APPROVED** [review]
Looks great! There are some straightforward conflicts, please resolve them and we can ship it =)

**Comment by jonatanklosko** [comment]
Deployed, great work :rocket:

**Comment by zeecho** [comment]
Thanks Jonatan!

**Pull request merged**
