### PR TITLE
Add locale flag to server-status page because I think it looks cool.

### PR DESCRIPTION
**Pull request by jfly**
Here's what it looks like now:

image

### CODE REVIEW

**Comment by jonatanklosko** [comment]
What about putting it on the left side of the locale name? This would keep the flags aligned =)

**Comment by jfly** [comment]
Good idea! I've updated the code accordingly. Ran into a weird bootstrap/html-ism with whitespace while I was at it, too =(.

The original version got rid of the space between the label and the badge. See:

image

The solution was to make sure there is no leading or trailing whitespace inside of the bootstrap `span.label` elements: http://stackoverflow.com/a/25879479. So now we have one long, gross line of erb code.

**Comment by jonatanklosko** [comment]
LGTM! Neat idea =)

**Comment by larspetrus** [comment]
This feels like a different page than the server runtime status,

**Comment by jfly** [comment]
Maybe someday we separate this out into a `i18n-status` page or maybe `/server-status/i18n`?

**Comment by larspetrus** [comment]
That's what I was thinking.

Having it under server-status makes me uncomfortable since this is all in git, and has nothing to do with the live server. The target audiences are also different.

**Comment by jfly** [comment]
For anyone following along here, I've created #1269 to track separating our translation statuses from our server-status.

**Pull request merged**
