### PR TITLE
Update the structure.sql dump using MySQL 8

### PR DESCRIPTION
**Pull request by viroulep**
I updated my local setup to MySQL 8 and notice there was a huge diff in the structure when running migrations.
This is the dump when running `bin/rails db:structure:dump` on production, so I believe we should update the repo to be accurate with what is on production.
@jfly, @tussosedan what do you think?

### CODE REVIEW

**Comment by viroulep** [comment]
Travis is unhappy about this:

> ERROR 1839 (HY000) at line 14 in file: '/home/travis/build/thewca/worldcubeassociation.org/WcaOnRails/db/structure.sql': @@GLOBAL.GTID_PURGED can only be set when @@GLOBAL.GTID_MODE = ON.

So I'll get rid of it.

**Comment by tussosedan** [comment]
If that's the dump of the production DB, then I was likely wrong about the dev export causing the diff. Syncing the repo with the current prod dump sounds like a good idea to me.
@jfly @jonatanklosko what do you think?

**Comment by jonatanklosko** [comment]
Ideally there would be no diff when running migrations locally, as that's what we've always aimed for.

**Comment by viroulep** [comment]
I have some more diff locally, most notably my mysql client uses the `utf8mb4` charset, whereas on production it seems to use just `utf8` (which is weird as `utf8mb4` is the default on mysql 8.0.1+).

Can you guys check locally what you get?

**Comment by tussosedan** [comment]
Local client settings are not in the repo, are they? Where do you see the diff?

**Comment by viroulep** [comment]
I ran `bin/rails db:structure:dump` over that branch :)

**Comment by tussosedan** [comment]
After cloning this branch, and running a structure dump locally, these are the only diffs I get!
Surprisingly the client charset is utf8, as in prod. For reference, I'm running mysql 8.0 in a docker container.


```
diff --git a/WcaOnRails/db/structure.sql b/WcaOnRails/db/structure.sql
index 888efd0b..a34e7850 100644
--- a/WcaOnRails/db/structure.sql
+++ b/WcaOnRails/db/structure.sql
@@ -9,8 +9,6 @@
 /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
 /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
 /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
-SET @MYSQLDUMP_TEMP_LOG_BIN = @@SESSION.SQL_LOG_BIN;
-SET @@SESSION.SQL_LOG_BIN= 0;
 DROP TABLE IF EXISTS `Competitions`;
 /*!40101 SET @saved_cs_client     = @@character_set_client */;
 /*!40101 SET character_set_client = utf8 */;
@@ -1374,7 +1372,6 @@ CREATE TABLE `wcif_extensions` (
 /*!50001 SET character_set_client      = @saved_cs_client */;
 /*!50001 SET character_set_results     = @saved_cs_results */;
 /*!50001 SET collation_connection      = @saved_col_connection */;
-SET @@SESSION.SQL_LOG_BIN = @MYSQLDUMP_TEMP_LOG_BIN;
 /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
 
 /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
```

**Comment by viroulep** [comment]
Yeah I don't get it :(

**Comment by jonatanklosko** [comment]
No diff for me!

**Comment by viroulep** [comment]
Yeah let's merge this then

**Pull request merged**
