### PR TITLE
Include message about middle name.

### LINKED ISSUE #1747: Competitors include middle name when registering
When creating an accuont on the WCA website, people will see this;

FULL NAME
[text field]
Enter your full name correctly, for example Stefan Pochmann. Not sloppily like s pochman.

I have found that this results in many people entering their full legal name (that's what it asks for, right?) , which looks extremely out of place in English speaking countries and competitions.  Of course, this is common practice in some parts of the world.

After a brief discussion with some of the software team and Board members, we agreed that it would be reasonable to add the following line to (at least) the English version of the website 

"Middle names or initials are optional, but can be included if it is customary in your region." 

It sounds like this is something that could also be removed for specific translations of the website where having this line would be unnecessary, such as the Spanish version.

### PR DESCRIPTION
**Pull request by pedrosino**
Fixes #1747 
Let me know if <'br /> is not the way to go here...

### CODE REVIEW

**Comment by jfly** [comment]
Could you add a screenshot? Otherwise, LGTM!

**Comment by pedrosino** [comment]
I would, but can't run the server locally :( (see slack)

**Comment by jfly** [comment]
I did see the slack messages, sounds like Philippe gave you the same advice I would. Please keep notes on whatever you have to do to get things working again so we can update our instructions for future developers.

In the mean time, there's always staging :)

**Comment by pedrosino** [comment]
image

**Comment by jfly** [comment]
LGTM!

**Comment by SAuroux** [comment]
As already stated in the previous discussion, I absolutely object the "initials" part. Reading this text I could absolutely register with "S. A." since "initials are optional" = "initials are an option".

**Comment by pedrosino** [comment]
Would "middle names/initials" work better?

James said about your concern:
> Isn't that what the "enter your name completely,  not sloppily like s pochman" part is for?

**Comment by SAuroux** [comment]
I know what James said, and his thought is simply wrong in my opinion. If we say that "initials are optional", we clearly say that initials are not part of what we mean by "sloppily".

And sorry, but the remaining text's logic makes me cringe as well. It first says that middle names are optional, then "but they can be included...". Should we add as well that it is also possible to not include them? Because then we have the full definition of "optional". ;)

Why not simply: "Middle names (either full or as initials) are optional."

**Comment by SAuroux** [comment]
PS: It seems to me that everyone except me naturally connects "initials" to middle names exclusively. Am I missing something or is everyone else just forgetting that first names and last names can also be written as initials?

**Comment by pedrosino** [comment]
> Why not simply: "Middle names (either full or as initials) are optional."
I like it. See #1769

> PS: It seems to me that everyone except me naturally connects "initials" to middle names exclusively. Am I missing something or is everyone else just forgetting that first names and last names can also be written as initials?
I don't make the connection to first names because that is just weird here. No one would call me "P. Santos", except maybe in academic papers or something (which would be like GUIMARAES, P. S.)
Using two initials is also not common at all. People may be called "Pedro Henrique" (both Pedro and Henrique are "first names", so this is a "compound name"), but you never see someone introducing himself as P.H. or PH

I wonder why people in the US have a middle name if they never use it...is there some kind of rule on names? Can someone be named just Joe Davis? Can you be Joe Davis Smith?

**Comment by SAuroux** [comment]
And exactly these kinds of different conventions around the world requires us to be absolutely unambiguous with our website texts! ;)

Here in German, most people basically ignore their middle names for their whole life. Even if I had a middle name, I would definitely refer "initials" to my first or last name. For instance, I use SA or S. Auroux regularly at work.

**Pull request merged**
