### PR TITLE
Add TNoodle 0.15.0

### PR DESCRIPTION
**Pull request by campos20**
You can see what's new [here](https://github.com/thewca/tnoodle/releases/tag/v0.15.0).

### CODE REVIEW

**Comment by jfly** [comment]
LGTM! There should be a second PR to go with this one, right?

**Comment by jfly** [comment]
Oh, and please don't merge this up until you've gotten approval from @thewca/wrc-team as well.

**Comment by campos20** [comment]
Yes, there will be a second PR. And I'll wait before making the merge since this is the first time I'm doing this :)

**Comment by lgarron** [comment]
Please land https://github.com/thewca/worldcubeassociation.org/pull/4307 and this as soon as you can and I'll send out an announcement!

Could you also help draft an announcement similar to https://www.worldcubeassociation.org/posts/tnoodle-0-14-0 /

**Comment by campos20** [comment]
TNoodle-WCA-0.15.0 is now available on https://www.worldcubeassociation.org/regulations/scrambles/
The following changes have been made, since TNoodle-WCA-0.14.0:

# Changes visible to the regular competitor:

* Better spacing on FMC cutout sheets.
* Competitor can fill competition name on FMC filling sheet.

# Changes visible to staff members:

* Prevent MBLD from being set to 1 cube (prevent input mistakes).
* Show table with rounds and groups for each event when generating scrambles for a competition.
* Option to print ordered scrambles matching the schedule.

Upcoming competitions should use TNoodle-WCA-0.15.0 to generate new scrambles, when possible. However, since we have just a few changes that directly affect competitors, TNoodle-WCA-0.14.0 will briefly remain an officially permitted version (competition scrambles for the coming week that have already been generated using TNoodle-WCA-0.14.5 can still be used).

Please remember that official competitions must use a current version of the official scramble program. This is always available from:
https://www.worldcubeassociation.org/regulations/scrambles/

**Pull request merged**
