### PR TITLE
Add pt-BR translation.

### PR DESCRIPTION
**Pull request by pedrosino**
#1055 should be merged first, I guess.

### CODE REVIEW

**Comment by viroulep** [comment]
Yes indeed :)

That's awesome, looks like pt-BR has the same pluralization rules as English, so you should have had trouble with that!

I think the errors may come from the activation of the locale in momentjs: could you try with "pt-br" instead of "pt-BR"?

**Comment by pedrosino** [comment]
>That's awesome, looks like pt-BR has the same pluralization rules as English, so you should have had trouble with that!

what do you mean?

**Comment by viroulep** [comment]
Oh you just did so :)

Any feedback on the doc so far?

> what do you mean?

I mean that some languages may need more than "one" and "other" keys for the pluralization of a key.
eg:
```yaml
    days:
      #original_hash: 2d8a6f7
      one: 1 dia
      #original_hash: 7a5ab1d
      other: '%{count} dias'
```

in Russian you need some more keys:
```yaml
    days:
      one: 1 день
      few: '%{count} дня'
      many: '%{count} дней'
```

Which could have give you some manual work!

**Comment by pedrosino** [comment]
How long do you think it will take for #1055 to be merged? I can wait until there, probably.

**Comment by viroulep** [comment]
Not sure, I'd like to wait until @jonatanklosko has finished the support for pluralization in his app, I think that's important enough to wait for it!

**Comment by pedrosino** [comment]
Ah, I'm not familiar with that. But I was under the impression that your translation was ready and the infrastructure too, so we could merge this and then once @jonatanklosko is finished with that we make the whole thing public, so delegates can make other translations.

**Comment by jfly** [comment]
@pedrosino, the problem is that #1055 does make this whole thing public (there will be a locale switcher on the WCA homepage). I personally would like to let our delegates (and the board!) know about this change *before* we push it to the WCA website.

**Comment by viroulep** [comment]
Maybe "this" refers to the current PR :p

**Comment by pedrosino** [comment]
> Maybe "this" refers to the current PR :p

If you mean

> ... so we could merge **_this_** and then once ...

then I meant #1055, sorry :P

**Comment by viroulep** [comment]
As @jfly made me realize, it could be nice to give Delegates some times to work on translations, and push live all we've got at once. So that's what we'll do, I'll send the mail tomorrow, and we should merge all the translations that are sent before activating them all and merge #1055.
So feel free to update your translation after #1097 and #1100 are merged, and please merge this one when ready :)

**Comment by viroulep** [comment]
We discussed this offline, turned out my spec for the momentjs activation was a bit off: the rails momenjs gem uses downcase locale code, where everywhere else the second part (here "BR") is uppercase.

Thanks for fixing the spec, LGTM :) (when the unused key error is fixed)

**Pull request merged**
