### PR TITLE
Include competition short name in WCIF

### PR DESCRIPTION
**Pull request by jonatanklosko**
I think it's useful to have the short name as an alternative as well. I will edit the specification doc once this gets approved =)

### CODE REVIEW

**Comment by jfly** [comment]
Sure, this definitely is useful for applications to present a human readable competition name. LGTM!

**Comment by jfly** [comment]
Oh, when you added this, I didn't realize we already have a competition name field in the WCIF. If you look at the create competition page: https://www.worldcubeassociation.org/competitions/new, you'll see there is no way to actually set the short name, we set it to the name. The only reason cellName still exists in our database is to avoid breaking PHP code =(

**Comment by jonatanklosko** [comment]
@jfly I don't think you're right about this. If you go to a edit page, you will see it's an editable field. See the code
https://github.com/thewca/worldcubeassociation.org/blob/484c3f7eb684a9b435db84da53778c08c6d6644d/WcaOnRails/app/views/competitions/_competition_form.html.erb#L28-L30
And the model constraints
https://github.com/thewca/worldcubeassociation.org/blob/484c3f7eb684a9b435db84da53778c08c6d6644d/WcaOnRails/app/models/competition.rb#L110

https://github.com/thewca/worldcubeassociation.org/blob/484c3f7eb684a9b435db84da53778c08c6d6644d/WcaOnRails/app/models/competition.rb#L121

**Comment by jfly** [comment]
Whoops, I'm crazy! Thanks for the quick response.

**Pull request merged**
