### PR TITLE
Added Cookie Banner for Cookie Law #18

### PR DESCRIPTION
**Pull request by notrichardpeng**
Using the cookies_eu gem: https://github.com/infinum/cookies_eu

image

### CODE REVIEW

**Comment by notrichardpeng** [comment]
Hey I'm fairly new to pull requests, I might need to look up how to separate this PR from the previous PR that I made. 
image

**Comment by Jambrose777** [comment]
> Hey I'm fairly new to pull requests, I might need to look up how to separate this PR from the previous PR that I made.

Ya here are the steps to do that (actually has to do with a branching strategy):
1) You'll want to set up a master branch to be exactly like wca's master branch and an upstream remote. ([link](https://devconnected.com/how-to-set-upstream-branch-on-git/#:~:text=The%20easiest%20way%20to%20set,u%E2%80%9D%20option%20for%20upstream%20branch.&text=Alternatively%2C%20you%20can%20use%20the,the%20%E2%80%9C%2Du%E2%80%9D%20option.&text=As%20an%20example%2C%20let's%20say,branch%E2%80%9D%20using%20the%20checkout%20command.))
2) Whenever you start work on a new issue, you'll create a new branch off of your master to do so:
- `git checkout master`
- `git fetch upstream`
- `git merge upstream/master`
- `git checkout -b my-new-feature-branch`
- Or something similar to the above
3) for this PR you'll need to do steps 1 and 2, then transfer the relevant commits to your new branch 
- `git checkout my-new-feature-branch`
- `git cherry-pick <commitId>`
- You can use `git log` on the dev branch to get the relevant commit ids that you'll need to cherry pick.

**Comment by gregorbg** [comment]
Jacob's instructions are correct, thank you for the thorough explanation! In newer versions of git, `git checkout -b branch` has been replaced with `git switch -c branch` but that doesn't change the fact that the general description is accurate.

Essentially, a Pull Request on GitHub is nothing more than a "fancy git merge" with moderation and discussion features. At the top of the page right below your PR title you will see a text about `wants to merge into thewca:foo from developer:bar` branch references. Essentially every commit from `developer:bar` that is not on `thewca:foo` will get added through the PR, but if you work on separate features you have to create them on separate branches and switch between them.

**Comment by notrichardpeng** [comment]
Thanks for the detailed responses guys. I thought one branch would be enough, turns out each feature needs a new branch.

**Pull request closed without merging**
