### PR TITLE
Change column name region to location

### PR DESCRIPTION
**Pull request by danieljames-dj**
Once the [regions PR](https://github.com/thewca/worldcubeassociation.org/pull/8009) is live, we might get confused between `region` and `region_id`. While `region_id` stands for the region of regions table, `region` stands for actually "location". Hence, renaming `region` to `location`.

(I initially thought of combining with other PR, but I didn't want to make the other PR more complex, hence did this separately)

### CODE REVIEW

**Comment by dunkOnIT** [comment]
@danieljames-dj is this still relevant given that #8120 is now closed?

**Comment by danieljames-dj** [comment]
Hi @dunkOnIT, yes it is. This is just an improvement to that column name of users table. This will also be really help in implementation of regions with new model.

**Comment by dunkOnIT** [comment]
Ok cool! What is required before merging? Just reviews?

**Comment by danieljames-dj** [comment]
Yes :-)

**Comment by dunkOnIT** [comment]
This is an interesting one, as if we miss something in review it could cause a spectacular failure in production :P Do you have any thoughts on how we mitigate that risk / how confident are you that you caught all usages of `region` and changed them to `location`? 

Review steps:
- [ ] Make sure that all appropriate instances of `region` have been changed to location 
- [ ] Test a core set of critical functions - can we make this an automated process somehow? (_It would alleviate a lot of anxiety/uncertainty around core changes like this. Perhaps our test suite already covers them?_)

**Comment by danieljames-dj** [comment]
Hi Duncan, I've made sure all instances of region has been changed to location. Sorry that I didn't understand what you mean by critical functions. Is it actions like 'view delegates page', 'view user edit page', etc where we use the region?

**Comment by danieljames-dj** [comment]
I'll explain little more about why I actually need this PR to work on the delegates restructuring. I've already [created a PR](https://github.com/thewca/worldcubeassociation.org/pull/8300) to create the groups and roles table with implementation of one group. For the implementation of delegates, I'm planning to do in different phases because doing it in a single PR is really difficult for me.

In the first phase, I'll be creating all the regions in groups table, and map all the delegates under corresponding region without changing anything else. For mapping delegates under a region, I have to introduce region_id in users table, which will show the region they belong to. At that time, if both region and region_id exists in users table and if there is no relation between them, then it will cause confusion. Also, in the final delegates_metadata table, the current region column will be named under location column. So, renaming it now will really help in coding more easily.

**Comment by dunkOnIT** [comment]
Hey Daniel Thanks so much for the detail there. It sounds like a really good change. 

We should be able to get this through pretty quickly - I'll grep and double-check that "region" has been changed to "location" when appropriate, and then we'll deploy to staging and ensure that core functionality is working as expected.

The "critical functions" thing is really outside the scope of this PR, more just me thinking about our testing in general. The thinking is basically - we have a set of critical functions that the WCA website provides to its users - competition creation, registration, results posting, etc. In theory, identifying those critical functions and making sure that they continue to function would help us push these changes with a lot of confidence. Many of these cases are already covered in our test suite, but I'm not exactly sure how comprehensive they are.

**Review by dunkOnIT — APPROVED** [review]
Approved after (partial) manual review, and confirmation with Gregor and Finn.

Deployment note: Migration must be run manually when deploying.

**Comment by danieljames-dj** [comment]
Thanks @dunkOnIT, can you please merge this PR and run the migration in server? I can't do this from my side as I don't have access to run migration in server.

**Comment by dunkOnIT** [comment]
Sure thing - I'll probably do it tomorrow morning with Finn, as I haven't run migrations on prod before.

**Pull request merged**
