### PR TITLE
Improving visualization on Teams & Committees page

### PR DESCRIPTION
**Pull request by moralsh**
Added  2 variables for 2 colors (dark-blue and dark-green) and used those two colors for leader and senior members badges. Also added border-radius to the avatars and some minor fixes so the avatars show up centered within the badge

### CODE REVIEW

**Comment by viroulep** [comment]
Adding the screenshot you posted on Slack:
bradandpadding

Can you confirm the screenshot is still accurate with regard to the changes suggested here?
As some other people commented on Slack, I also think it looks better than what we have now!

Overall the code looks good to me, but the history is a mess and still conflicts with the master branch.
Would you be comfortable with fixing that technical issue?
Otherwise I guess a WST member could look into it.

As far as I'm concerned, my way to handle this would be to take [the diff](https://patch-diff.githubusercontent.com/raw/thewca/worldcubeassociation.org/pull/4678.diff) of that PR and try to apply it in a clean branch checked out from master.

**Comment by moralsh** [comment]
yes, the screenshot is accurate, It might even look a bit better now that all badges are fixed.
Screenshot from 2019-10-05 19-49-28

My fork got messed up after a wrongly done rebase (my guess) and all those commits was me trying to fix it, I'll follow your advice.

Once I solve this one I'll commit another change I have ready, adding links to profile on that same page, I was planning to do a different PR, should I use this one?

**Comment by viroulep** [comment]
I'd suggest creating another PR since the change is not related to what you submitted here.

More generally I'd suggest you to always create a branch separate from master when creating some changes on the website.
This way you can keep your master branch clean and sync it up with `thewca` periodically, and you can work on several changes without worrying that they mess up with each others.
(for this particular PR you will probably have to force push your cleaned up commit to your master branch, since the PR was made from your master branch)

**Comment by moralsh** [comment]
I've been working with GIt for around 10 years and always work on branches, even for fixing typos, only applying changes to master via merge, I really don't know why I haven't done the same here, I guess it's been due to all changes I've contributed being very minor. 

What I'm going to do is clean my fork once and for all and start working that way, but that will be tomorrow, thanks for the hints!

**Comment by viroulep** [comment]
Deployed, thanks @moralsh!

**Comment by moralsh** [comment]
Thanks @viroulep !! I'll prepare the next one!

**Pull request merged**
