### PR TITLE
Change full name message.

### PR DESCRIPTION
**Pull request by pedrosino**

### CODE REVIEW

**Comment by larspetrus** [comment]
Obviously this works, but I don't think we've agreed to doing this yet.

**Comment by Luis-J-Ianez** [comment]
I'd suggest adding one good example for every main language.  For good example I mean one in which it's clear that the first name goes before the last name (i.e everyone speaking this language easily recognizes the first name like a first name and the last name like a last name).  Additionally, for languages where it's usual to have more that one first name and/or more than one last name, I'd put longest names, so that it's clear that you can use several words for every name.  Example:

> English = John G. Smith
> Español = Juan Carlos Gómez Pérez
> Nihongo (日本) = Hideo Kojima (小島秀夫)

We could use only good names of famous people.

**Comment by jonatanklosko** [comment]
A sidenote: when we'll be translating the page to many languages, it will be nice to just add country-specific example in this hint =)

**Comment by viroulep** [comment]
I did something similar in the [French](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/config/locales/fr.yml#L115) translation where I tweaked one of the "bad" example to avoid the common "Firstname NAME" spelling.

The hint doesn't have to be only one line so it's definitely possible to put something longer with a list of common spelling and common mistakes.

**Comment by jfly** [comment]
Closing due to inactivity. See our new policy: [PRs that have gone 3 months without activity are subject to being closed.](https://github.com/thewca/worldcubeassociation.org/wiki/Merging-and-deploying)

**Pull request closed without merging**
